#!/bin/bash
# generate-secrets.sh
# Generates Secrets.generated.swift from environment variables.
# Called by CI before building, or manually for local development.
#
# Usage:
#   SUPABASE_URL="https://xxx.supabase.co" SUPABASE_ANON_KEY="eyJ..." ./scripts/generate-secrets.sh
#
# The generated file is gitignored and should never be committed.
#
# IMPORTANT: If the file already contains real (non-empty) secrets and no
# environment variables are provided, the script will SKIP overwriting.
# This prevents the Xcode pre-build phase from clobbering secrets that
# were injected by CI before the build started.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$PROJECT_DIR/DesMoinesInsider/Configuration/Secrets.generated.swift"

# Read from environment variables (set by CI, xcconfig, or .env)
SUPABASE_URL_VALUE="${SUPABASE_URL:-}"
SUPABASE_ANON_KEY_VALUE="${SUPABASE_ANON_KEY:-}"

# If env vars aren't set, try reading from Secrets.xcconfig
XCCONFIG_FILE="$PROJECT_DIR/Secrets.xcconfig"
if [ -z "$SUPABASE_URL_VALUE" ] && [ -f "$XCCONFIG_FILE" ]; then
    SUPABASE_URL_VALUE=$(grep "^SUPABASE_URL" "$XCCONFIG_FILE" | head -1 | sed 's/^SUPABASE_URL[[:space:]]*=[[:space:]]*//' | sed 's/[[:space:]]*$//')
fi
if [ -z "$SUPABASE_ANON_KEY_VALUE" ] && [ -f "$XCCONFIG_FILE" ]; then
    SUPABASE_ANON_KEY_VALUE=$(grep "^SUPABASE_ANON_KEY" "$XCCONFIG_FILE" | head -1 | sed 's/^SUPABASE_ANON_KEY[[:space:]]*=[[:space:]]*//' | sed 's/[[:space:]]*$//')
fi

# ──────────────────────────────────────────────────────────────────────
# GUARD: If no new values are available but the file already has real
# secrets, do NOT overwrite. This protects against the Xcode pre-build
# script clobbering secrets that CI wrote before xcodegen/xcodebuild.
# ──────────────────────────────────────────────────────────────────────
if [ -z "$SUPABASE_URL_VALUE" ] && [ -z "$SUPABASE_ANON_KEY_VALUE" ] && [ -f "$OUTPUT_FILE" ]; then
    # Check if the existing file has non-empty values
    EXISTING_URL=$(grep 'supabaseURL' "$OUTPUT_FILE" 2>/dev/null | sed 's/.*= "\(.*\)"/\1/' || true)
    if [ -n "$EXISTING_URL" ] && [ "$EXISTING_URL" != "" ]; then
        echo "✅ Secrets.generated.swift already has values — skipping (no env vars set)"
        exit 0
    fi
fi

# Warn if values are missing (build will succeed but app will show config error)
if [ -z "$SUPABASE_URL_VALUE" ]; then
    echo "warning: SUPABASE_URL is not set. The app will show a configuration error at launch."
fi
if [ -z "$SUPABASE_ANON_KEY_VALUE" ]; then
    echo "warning: SUPABASE_ANON_KEY is not set. The app will show a configuration error at launch."
fi

# Generate the Swift file
cat > "$OUTPUT_FILE" << SWIFT
// Secrets.generated.swift
// AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-secrets.sh
// This file is gitignored and must never be committed.

import Foundation

/// Build-time injected secrets. Generated from environment variables or Secrets.xcconfig.
enum GeneratedSecrets {
    static let supabaseURL = "$SUPABASE_URL_VALUE"
    static let supabaseAnonKey = "$SUPABASE_ANON_KEY_VALUE"
}
SWIFT

echo "✅ Generated Secrets.generated.swift"
if [ -n "$SUPABASE_URL_VALUE" ]; then
    echo "   SUPABASE_URL: ${SUPABASE_URL_VALUE:0:30}..."
else
    echo "   SUPABASE_URL: (empty)"
fi
