/**
 * pSEO 2.0 — Phase 3: Detailed Page Type Schemas
 *
 * Each page type has a complete TypeScript interface annotated with:
 *   - // DETERMINISTIC — templated/computed, never varies per generation
 *   - // AI-FILL       — generated by Claude, varies per generation
 *   - // FROM-DB       — pulled from Supabase at render time
 *
 * Array fields include explicit min/max counts.
 * Enum types are fully enumerated.
 * Optional fields document when to include them.
 */

// ---------------------------------------------------------------------------
// Shared Enums
// ---------------------------------------------------------------------------

export type PageTypeId =
  | 'content-location'
  | 'content-audience'
  | 'content-temporal'
  | 'content-category'
  | 'content-location-audience'
  | 'content-location-temporal'
  | 'category-location'
  | 'audience-temporal'
  | 'category-temporal'
  | 'location-guide';

export type ContentTypeSlug =
  | 'things-to-do'
  | 'events'
  | 'restaurants'
  | 'attractions'
  | 'nightlife'
  | 'outdoors';

export type LocationSlug =
  | 'downtown'
  | 'east-village'
  | 'valley-junction'
  | 'drake'
  | 'beaverdale'
  | 'sherman-hill'
  | 'ingersoll'
  | 'west-des-moines'
  | 'ankeny'
  | 'urbandale'
  | 'johnston'
  | 'altoona'
  | 'clive'
  | 'waukee'
  | 'pleasant-hill'
  | 'windsor-heights';

export type AudienceSlug =
  | 'families'
  | 'date-night'
  | 'foodies'
  | 'budget'
  | 'tourists'
  | 'couples'
  | 'groups'
  | 'seniors'
  | 'pet-friendly';

export type TemporalSlug =
  | 'today'
  | 'this-weekend'
  | 'this-week'
  | 'spring'
  | 'summer'
  | 'fall'
  | 'winter'
  | 'january'
  | 'february'
  | 'march'
  | 'april'
  | 'may'
  | 'june'
  | 'july'
  | 'august'
  | 'september'
  | 'october'
  | 'november'
  | 'december';

export type CategorySlug =
  | 'italian'
  | 'mexican'
  | 'asian'
  | 'bbq'
  | 'brunch'
  | 'coffee'
  | 'steakhouse'
  | 'live-music'
  | 'festivals'
  | 'arts-culture'
  | 'sports'
  | 'farmers-markets'
  | 'museums'
  | 'parks';

export type RefreshSchedule = 'realtime' | 'daily' | 'weekly' | 'monthly' | 'seasonal' | 'evergreen';

export type RelationshipType = 'parent' | 'child' | 'sibling' | 'cross';

export type SectionType =
  | 'hero_intro'
  | 'curated_picks'
  | 'live_listings'
  | 'local_tips'
  | 'seasonal_context'
  | 'faq'
  | 'related_pages'
  | 'neighborhood_profile'
  | 'audience_callout'
  | 'map_embed'
  | 'cta_block';

export type SchemaOrgType =
  | 'WebPage'
  | 'CollectionPage'
  | 'ItemList'
  | 'FAQPage'
  | 'TouristDestination'
  | 'LocalBusiness';

// ---------------------------------------------------------------------------
// Shared Sub-Schemas
// ---------------------------------------------------------------------------

export interface PageMeta {
  page_type: PageTypeId;             // DETERMINISTIC
  generated_at: string;              // DETERMINISTIC — ISO 8601
  prompt_version: string;            // DETERMINISTIC — semver e.g. "2.0.0"
  model_used: string;                // DETERMINISTIC — e.g. "claude-sonnet-5"
  source_record_ids: string[];       // FROM-DB — UUIDs of items referenced (0-20)
  combination: Record<string, string>; // DETERMINISTIC — dimension slug pairs
  freshness_days: number;            // DETERMINISTIC — how many days before refresh
  refresh_schedule: RefreshSchedule; // DETERMINISTIC
  quality_score: number;             // DETERMINISTIC — 0.0-1.0, computed post-generation
  word_count: number;                // DETERMINISTIC — computed post-generation
}

export interface PageSeo {
  title: string;                     // DETERMINISTIC — from title template, max 60 chars
  description: string;               // AI-FILL — max 155 chars, must include CTA
  h1: string;                        // DETERMINISTIC — from H1 template
  keywords: string[];                // AI-FILL — exactly 5-8 keywords
  canonical_url: string;             // DETERMINISTIC — full URL with domain
  og_title: string;                  // DETERMINISTIC — same as title or shorter
  og_description: string;            // AI-FILL — same as description or shorter
  og_image: string;                  // DETERMINISTIC — default OG image path
  og_type: 'website' | 'article';   // DETERMINISTIC
  schema_type: SchemaOrgType;        // DETERMINISTIC
}

export interface HeroSection {
  headline: string;                  // AI-FILL — niche-aware, 8-15 words, no generic filler
  subheadline: string;               // AI-FILL — specific value proposition, 10-20 words
  intro: string;                     // AI-FILL — exactly 2-3 sentences, 40-60 words
}

export interface CuratedItem {
  name: string;                      // AI-FILL — business/venue/event name
  slug: string;                      // FROM-DB — link slug if exists, empty string if not
  description: string;               // AI-FILL — 2-3 sentences, 30-50 words
  why_we_recommend: string;          // AI-FILL — 1 sentence, specific reason
  insider_tip: string;               // AI-FILL — 1 sentence, local-only knowledge
  /** Include for restaurants and attractions only */
  price_range?: '$' | '$$' | '$$$' | '$$$$'; // AI-FILL
  /** Include when data available from DB */
  rating?: number;                   // FROM-DB — 1.0-5.0
  /** Include for places with physical locations */
  address?: string;                  // FROM-DB
  tags: string[];                    // AI-FILL — 2-4 tags
}

export interface FaqItem {
  question: string;                  // AI-FILL — matches real search query phrasing
  answer: string;                    // AI-FILL — 2-3 sentences, 30-60 words, includes "Des Moines"
}

export interface RelatedPage {
  title: string;                     // DETERMINISTIC — generated from dimension templates
  url: string;                       // DETERMINISTIC — relative path
  relationship: RelationshipType;    // DETERMINISTIC — computed from dimension overlap
  description: string;               // AI-FILL — 1 sentence, why this link helps the reader
}

export interface CtaBlock {
  heading: string;                   // AI-FILL — action-oriented, 5-10 words
  body: string;                      // AI-FILL — 1-2 sentences
  primary_button_text: string;       // DETERMINISTIC — "Explore Events" / "Find Restaurants" etc.
  primary_button_url: string;        // DETERMINISTIC
  /** Include only when newsletter/subscription CTA is appropriate */
  secondary_button_text?: string;    // DETERMINISTIC
  /** Include only when newsletter/subscription CTA is appropriate */
  secondary_button_url?: string;     // DETERMINISTIC
}

export interface Breadcrumb {
  name: string;                      // DETERMINISTIC
  url: string;                       // DETERMINISTIC
}

// ---------------------------------------------------------------------------
// Page Type 1: Content + Location
// Example: "Restaurants in East Village"
// ---------------------------------------------------------------------------

export interface ContentLocationSchema {
  meta: PageMeta & {
    combination: {
      content_type: ContentTypeSlug;   // DETERMINISTIC
      location: LocationSlug;          // DETERMINISTIC
    };
    freshness_days: 14;                // DETERMINISTIC — refresh every 2 weeks
    refresh_schedule: 'weekly';        // DETERMINISTIC
  };
  seo: PageSeo & {
    schema_type: 'CollectionPage';     // DETERMINISTIC
  };
  hero: HeroSection;
  curated_picks: {
    heading: string;                   // AI-FILL — e.g. "Best Restaurants in East Village"
    items: CuratedItem[];              // AI-FILL + FROM-DB — exactly 6-8 items
  };
  neighborhood_profile: {
    heading: string;                   // AI-FILL — e.g. "About East Village"
    content: string;                   // AI-FILL — 100-150 words, character + logistics
    walkability: 'high' | 'medium' | 'low'; // AI-FILL
    parking_difficulty: 'easy' | 'moderate' | 'difficult'; // AI-FILL
    vibe: string;                      // AI-FILL — 3-5 word descriptor
  };
  local_tips: {
    heading: string;                   // AI-FILL
    tips: string[];                    // AI-FILL — exactly 4-6 tips, each 1-2 sentences
  };
  live_listings: {
    entity_type: 'events' | 'restaurants' | 'attractions'; // DETERMINISTIC
    filters: Record<string, string>;   // DETERMINISTIC — Supabase query filters
    limit: 12;                         // DETERMINISTIC
    sort_by: string;                   // DETERMINISTIC
  };
  faq: FaqItem[];                      // AI-FILL — exactly 4-6 items
  related_pages: RelatedPage[];        // DETERMINISTIC + AI-FILL — exactly 4-6 links
  cta: CtaBlock;
  breadcrumbs: Breadcrumb[];           // DETERMINISTIC — Home > ContentType > Location
  /** Include when location has lat/lng data */
  map_center?: { lat: number; lng: number }; // FROM-DB
}

// ---------------------------------------------------------------------------
// Page Type 2: Content + Audience
// Example: "Date Night Restaurants in Des Moines"
// ---------------------------------------------------------------------------

export interface ContentAudienceSchema {
  meta: PageMeta & {
    combination: {
      content_type: ContentTypeSlug;   // DETERMINISTIC
      audience: AudienceSlug;          // DETERMINISTIC
    };
    freshness_days: 30;                // DETERMINISTIC
    refresh_schedule: 'monthly';       // DETERMINISTIC
  };
  seo: PageSeo & {
    schema_type: 'CollectionPage';     // DETERMINISTIC
  };
  hero: HeroSection;
  audience_callout: {
    heading: string;                   // AI-FILL — speaks to the audience
    content: string;                   // AI-FILL — 80-120 words, second person "you"
    key_considerations: string[];      // AI-FILL — exactly 3-5 bullet points
  };
  curated_picks: {
    heading: string;                   // AI-FILL
    items: CuratedItem[];              // AI-FILL + FROM-DB — exactly 6-8 items
  };
  local_tips: {
    heading: string;                   // AI-FILL — audience-specific heading
    tips: string[];                    // AI-FILL — exactly 4-6 tips
  };
  live_listings: {
    entity_type: 'events' | 'restaurants' | 'attractions'; // DETERMINISTIC
    filters: Record<string, string>;   // DETERMINISTIC
    limit: 12;                         // DETERMINISTIC
    sort_by: string;                   // DETERMINISTIC
  };
  faq: FaqItem[];                      // AI-FILL — exactly 4-6 items, audience-specific
  related_pages: RelatedPage[];        // DETERMINISTIC + AI-FILL — exactly 4-6
  cta: CtaBlock;
  breadcrumbs: Breadcrumb[];           // DETERMINISTIC — Home > ContentType > Audience
}

// ---------------------------------------------------------------------------
// Page Type 3: Content + Temporal
// Example: "Events This Weekend in Des Moines"
// ---------------------------------------------------------------------------

export interface ContentTemporalSchema {
  meta: PageMeta & {
    combination: {
      content_type: ContentTypeSlug;   // DETERMINISTIC
      temporal: TemporalSlug;          // DETERMINISTIC
    };
    freshness_days: 1;                 // DETERMINISTIC — today/weekend refresh daily
    refresh_schedule: 'daily';         // DETERMINISTIC
  };
  seo: PageSeo & {
    schema_type: 'CollectionPage';     // DETERMINISTIC
  };
  hero: HeroSection;
  seasonal_context: {
    heading: string;                   // AI-FILL
    content: string;                   // AI-FILL — 100-150 words, weather + what's in season
    weather_note: string;              // AI-FILL — 1 sentence, current season weather
    /** Include for monthly/seasonal pages only */
    seasonal_highlights?: string[];    // AI-FILL — 3-5 seasonal items
  };
  curated_picks: {
    heading: string;                   // AI-FILL — time-aware heading
    items: CuratedItem[];              // AI-FILL + FROM-DB — exactly 6-8 items
  };
  local_tips: {
    heading: string;                   // AI-FILL
    tips: string[];                    // AI-FILL — exactly 4-6 tips, time-aware
  };
  live_listings: {
    entity_type: 'events' | 'restaurants' | 'attractions'; // DETERMINISTIC
    filters: Record<string, string>;   // DETERMINISTIC — includes date range
    limit: 12;                         // DETERMINISTIC
    sort_by: 'date';                   // DETERMINISTIC
  };
  faq: FaqItem[];                      // AI-FILL — exactly 4-6 items
  related_pages: RelatedPage[];        // DETERMINISTIC + AI-FILL — exactly 4-6
  cta: CtaBlock;
  breadcrumbs: Breadcrumb[];           // DETERMINISTIC — Home > ContentType > Temporal
}

// ---------------------------------------------------------------------------
// Page Type 4: Content + Category
// Example: "Best Italian Restaurants in Des Moines"
// ---------------------------------------------------------------------------

export interface ContentCategorySchema {
  meta: PageMeta & {
    combination: {
      content_type: ContentTypeSlug;   // DETERMINISTIC
      category: CategorySlug;          // DETERMINISTIC
    };
    freshness_days: 30;                // DETERMINISTIC
    refresh_schedule: 'monthly';       // DETERMINISTIC
  };
  seo: PageSeo & {
    schema_type: 'ItemList';           // DETERMINISTIC
  };
  hero: HeroSection;
  curated_picks: {
    heading: string;                   // AI-FILL — category-specific
    items: CuratedItem[];              // AI-FILL + FROM-DB — exactly 8-12 items
    /** Include for cuisine categories only */
    cuisine_context?: string;          // AI-FILL — 2-3 sentences on this cuisine in DSM
  };
  local_tips: {
    heading: string;                   // AI-FILL
    tips: string[];                    // AI-FILL — exactly 4-6 tips, category-specific
  };
  live_listings: {
    entity_type: 'events' | 'restaurants' | 'attractions'; // DETERMINISTIC
    filters: Record<string, string>;   // DETERMINISTIC — includes category filter
    limit: 12;                         // DETERMINISTIC
    sort_by: string;                   // DETERMINISTIC
  };
  faq: FaqItem[];                      // AI-FILL — exactly 4-6 items
  related_pages: RelatedPage[];        // DETERMINISTIC + AI-FILL — exactly 4-6
  cta: CtaBlock;
  breadcrumbs: Breadcrumb[];           // DETERMINISTIC — Home > ContentType > Category
}

// ---------------------------------------------------------------------------
// Page Type 5: Content + Location + Audience (triple)
// Example: "Family Restaurants in Downtown Des Moines"
// ---------------------------------------------------------------------------

export interface ContentLocationAudienceSchema {
  meta: PageMeta & {
    combination: {
      content_type: ContentTypeSlug;   // DETERMINISTIC
      location: LocationSlug;          // DETERMINISTIC
      audience: AudienceSlug;          // DETERMINISTIC
    };
    freshness_days: 30;                // DETERMINISTIC
    refresh_schedule: 'monthly';       // DETERMINISTIC
  };
  seo: PageSeo & {
    schema_type: 'CollectionPage';     // DETERMINISTIC
  };
  hero: HeroSection;
  audience_callout: {
    heading: string;                   // AI-FILL
    content: string;                   // AI-FILL — 80-120 words
    key_considerations: string[];      // AI-FILL — exactly 3-5
  };
  neighborhood_profile: {
    heading: string;                   // AI-FILL
    content: string;                   // AI-FILL — 80-100 words (shorter in triple combo)
    walkability: 'high' | 'medium' | 'low'; // AI-FILL
    parking_difficulty: 'easy' | 'moderate' | 'difficult'; // AI-FILL
    vibe: string;                      // AI-FILL
  };
  curated_picks: {
    heading: string;                   // AI-FILL
    items: CuratedItem[];              // AI-FILL + FROM-DB — exactly 6-8 items
  };
  local_tips: {
    heading: string;                   // AI-FILL
    tips: string[];                    // AI-FILL — exactly 4-6 tips
  };
  live_listings: {
    entity_type: 'events' | 'restaurants' | 'attractions'; // DETERMINISTIC
    filters: Record<string, string>;   // DETERMINISTIC
    limit: 12;                         // DETERMINISTIC
    sort_by: string;                   // DETERMINISTIC
  };
  faq: FaqItem[];                      // AI-FILL — exactly 4 items (shorter for triple)
  related_pages: RelatedPage[];        // DETERMINISTIC + AI-FILL — exactly 4-6
  cta: CtaBlock;
  breadcrumbs: Breadcrumb[];           // DETERMINISTIC — Home > ContentType > Location > Audience
  map_center?: { lat: number; lng: number }; // FROM-DB
}

// ---------------------------------------------------------------------------
// Page Type 6: Content + Location + Temporal (triple)
// Example: "Events in Downtown Des Moines This Weekend"
// ---------------------------------------------------------------------------

export interface ContentLocationTemporalSchema {
  meta: PageMeta & {
    combination: {
      content_type: ContentTypeSlug;   // DETERMINISTIC
      location: LocationSlug;          // DETERMINISTIC
      temporal: TemporalSlug;          // DETERMINISTIC
    };
    freshness_days: 1;                 // DETERMINISTIC
    refresh_schedule: 'daily';         // DETERMINISTIC
  };
  seo: PageSeo & {
    schema_type: 'CollectionPage';     // DETERMINISTIC
  };
  hero: HeroSection;
  seasonal_context: {
    heading: string;                   // AI-FILL
    content: string;                   // AI-FILL — 80-100 words
    weather_note: string;              // AI-FILL
  };
  neighborhood_profile: {
    heading: string;                   // AI-FILL
    content: string;                   // AI-FILL — 80-100 words
    walkability: 'high' | 'medium' | 'low'; // AI-FILL
    parking_difficulty: 'easy' | 'moderate' | 'difficult'; // AI-FILL
    vibe: string;                      // AI-FILL
  };
  curated_picks: {
    heading: string;                   // AI-FILL
    items: CuratedItem[];              // AI-FILL + FROM-DB — exactly 6-8 items
  };
  local_tips: {
    heading: string;                   // AI-FILL
    tips: string[];                    // AI-FILL — exactly 4-6 tips
  };
  live_listings: {
    entity_type: 'events' | 'restaurants' | 'attractions'; // DETERMINISTIC
    filters: Record<string, string>;   // DETERMINISTIC — includes date + location
    limit: 12;                         // DETERMINISTIC
    sort_by: 'date';                   // DETERMINISTIC
  };
  faq: FaqItem[];                      // AI-FILL — exactly 4 items
  related_pages: RelatedPage[];        // DETERMINISTIC + AI-FILL — exactly 4-6
  cta: CtaBlock;
  breadcrumbs: Breadcrumb[];           // DETERMINISTIC
  map_center?: { lat: number; lng: number }; // FROM-DB
}

// ---------------------------------------------------------------------------
// Page Type 7: Category + Location
// Example: "Best Italian in East Village"
// ---------------------------------------------------------------------------

export interface CategoryLocationSchema {
  meta: PageMeta & {
    combination: {
      category: CategorySlug;          // DETERMINISTIC
      location: LocationSlug;          // DETERMINISTIC
    };
    freshness_days: 30;                // DETERMINISTIC
    refresh_schedule: 'monthly';       // DETERMINISTIC
  };
  seo: PageSeo & {
    schema_type: 'ItemList';           // DETERMINISTIC
  };
  hero: HeroSection;
  neighborhood_profile: {
    heading: string;                   // AI-FILL
    content: string;                   // AI-FILL — 80-100 words
    walkability: 'high' | 'medium' | 'low'; // AI-FILL
    parking_difficulty: 'easy' | 'moderate' | 'difficult'; // AI-FILL
    vibe: string;                      // AI-FILL
  };
  curated_picks: {
    heading: string;                   // AI-FILL
    items: CuratedItem[];              // AI-FILL + FROM-DB — exactly 6-10 items
    /** Include for food categories, context on the cuisine scene in this location */
    cuisine_context?: string;          // AI-FILL — 2-3 sentences
  };
  local_tips: {
    heading: string;                   // AI-FILL
    tips: string[];                    // AI-FILL — exactly 4-6 tips
  };
  live_listings: {
    entity_type: 'events' | 'restaurants' | 'attractions'; // DETERMINISTIC
    filters: Record<string, string>;   // DETERMINISTIC
    limit: 12;                         // DETERMINISTIC
    sort_by: string;                   // DETERMINISTIC
  };
  faq: FaqItem[];                      // AI-FILL — exactly 4-6 items
  related_pages: RelatedPage[];        // DETERMINISTIC + AI-FILL — exactly 4-6
  cta: CtaBlock;
  breadcrumbs: Breadcrumb[];           // DETERMINISTIC
  map_center?: { lat: number; lng: number }; // FROM-DB
}

// ---------------------------------------------------------------------------
// Page Type 8: Audience + Temporal
// Example: "Family Things to Do This Weekend"
// ---------------------------------------------------------------------------

export interface AudienceTemporalSchema {
  meta: PageMeta & {
    combination: {
      audience: AudienceSlug;          // DETERMINISTIC
      temporal: TemporalSlug;          // DETERMINISTIC
    };
    freshness_days: 1;                 // DETERMINISTIC
    refresh_schedule: 'daily';         // DETERMINISTIC
  };
  seo: PageSeo & {
    schema_type: 'CollectionPage';     // DETERMINISTIC
  };
  hero: HeroSection;
  audience_callout: {
    heading: string;                   // AI-FILL
    content: string;                   // AI-FILL — 80-120 words
    key_considerations: string[];      // AI-FILL — exactly 3-5
  };
  seasonal_context: {
    heading: string;                   // AI-FILL
    content: string;                   // AI-FILL — 80-100 words
    weather_note: string;              // AI-FILL
  };
  curated_picks: {
    heading: string;                   // AI-FILL
    items: CuratedItem[];              // AI-FILL + FROM-DB — exactly 6-8 items
  };
  local_tips: {
    heading: string;                   // AI-FILL
    tips: string[];                    // AI-FILL — exactly 4-6 tips
  };
  live_listings: {
    entity_type: 'events';             // DETERMINISTIC — cross-entity for things-to-do
    filters: Record<string, string>;   // DETERMINISTIC
    limit: 12;                         // DETERMINISTIC
    sort_by: 'date';                   // DETERMINISTIC
  };
  faq: FaqItem[];                      // AI-FILL — exactly 4-6 items
  related_pages: RelatedPage[];        // DETERMINISTIC + AI-FILL — exactly 4-6
  cta: CtaBlock;
  breadcrumbs: Breadcrumb[];           // DETERMINISTIC
}

// ---------------------------------------------------------------------------
// Page Type 9: Category + Temporal
// Example: "Live Music This Summer in Des Moines"
// ---------------------------------------------------------------------------

export interface CategoryTemporalSchema {
  meta: PageMeta & {
    combination: {
      category: CategorySlug;          // DETERMINISTIC
      temporal: TemporalSlug;          // DETERMINISTIC
    };
    freshness_days: 7;                 // DETERMINISTIC
    refresh_schedule: 'weekly';        // DETERMINISTIC
  };
  seo: PageSeo & {
    schema_type: 'CollectionPage';     // DETERMINISTIC
  };
  hero: HeroSection;
  seasonal_context: {
    heading: string;                   // AI-FILL
    content: string;                   // AI-FILL — 100-150 words
    weather_note: string;              // AI-FILL
    seasonal_highlights?: string[];    // AI-FILL — 3-5 seasonal items for this category
  };
  curated_picks: {
    heading: string;                   // AI-FILL
    items: CuratedItem[];              // AI-FILL + FROM-DB — exactly 6-8 items
  };
  local_tips: {
    heading: string;                   // AI-FILL
    tips: string[];                    // AI-FILL — exactly 4-6 tips
  };
  live_listings: {
    entity_type: 'events' | 'restaurants' | 'attractions'; // DETERMINISTIC
    filters: Record<string, string>;   // DETERMINISTIC
    limit: 12;                         // DETERMINISTIC
    sort_by: string;                   // DETERMINISTIC
  };
  faq: FaqItem[];                      // AI-FILL — exactly 4-6 items
  related_pages: RelatedPage[];        // DETERMINISTIC + AI-FILL — exactly 4-6
  cta: CtaBlock;
  breadcrumbs: Breadcrumb[];           // DETERMINISTIC
}

// ---------------------------------------------------------------------------
// Page Type 10: Location Guide (hub page)
// Example: "Your Complete Guide to East Village"
// ---------------------------------------------------------------------------

export interface LocationGuideSchema {
  meta: PageMeta & {
    combination: {
      location: LocationSlug;          // DETERMINISTIC
    };
    freshness_days: 30;                // DETERMINISTIC
    refresh_schedule: 'monthly';       // DETERMINISTIC
  };
  seo: PageSeo & {
    schema_type: 'TouristDestination'; // DETERMINISTIC
  };
  hero: HeroSection;
  neighborhood_profile: {
    heading: string;                   // AI-FILL
    content: string;                   // AI-FILL — 150-200 words, comprehensive
    walkability: 'high' | 'medium' | 'low'; // AI-FILL
    parking_difficulty: 'easy' | 'moderate' | 'difficult'; // AI-FILL
    vibe: string;                      // AI-FILL — 3-5 word descriptor
    best_for: string[];                // AI-FILL — exactly 3-5 audience types
    getting_there: string;             // AI-FILL — 2-3 sentences on transportation
  };
  curated_picks: {
    heading: string;                   // AI-FILL — "Top Spots in [Location]"
    items: CuratedItem[];              // AI-FILL + FROM-DB — exactly 8-12 items (mix of types)
  };
  /** Location guides include a food & drink mini-section */
  dining_highlights: {
    heading: string;                   // AI-FILL
    content: string;                   // AI-FILL — 80-120 words on the food scene
    top_picks: string[];               // AI-FILL — exactly 3-5 restaurant names
  };
  local_tips: {
    heading: string;                   // AI-FILL — "Insider Tips for [Location]"
    tips: string[];                    // AI-FILL — exactly 6-8 tips (more for hub pages)
  };
  live_listings: {
    entity_type: 'events';             // DETERMINISTIC — show upcoming local events
    filters: Record<string, string>;   // DETERMINISTIC
    limit: 8;                          // DETERMINISTIC — fewer, it's a hub
    sort_by: 'date';                   // DETERMINISTIC
  };
  faq: FaqItem[];                      // AI-FILL — exactly 5-7 items (more for hub)
  related_pages: RelatedPage[];        // DETERMINISTIC + AI-FILL — exactly 6-8 (more links for hub)
  cta: CtaBlock;
  breadcrumbs: Breadcrumb[];           // DETERMINISTIC — Home > Guide > Location
  map_center: { lat: number; lng: number }; // FROM-DB — required for guides
}

// ---------------------------------------------------------------------------
// Union Type for all page schemas
// ---------------------------------------------------------------------------

export type AnyPseoSchema =
  | ContentLocationSchema
  | ContentAudienceSchema
  | ContentTemporalSchema
  | ContentCategorySchema
  | ContentLocationAudienceSchema
  | ContentLocationTemporalSchema
  | CategoryLocationSchema
  | AudienceTemporalSchema
  | CategoryTemporalSchema
  | LocationGuideSchema;

// ---------------------------------------------------------------------------
// Schema Lookup
// ---------------------------------------------------------------------------

/**
 * Mapping of page type IDs to their required sections.
 * Used by the generation pipeline to validate completeness.
 */
export const PAGE_TYPE_REQUIRED_SECTIONS: Record<PageTypeId, SectionType[]> = {
  'content-location': ['hero_intro', 'curated_picks', 'neighborhood_profile', 'local_tips', 'live_listings', 'faq', 'related_pages', 'cta_block'],
  'content-audience': ['hero_intro', 'audience_callout', 'curated_picks', 'local_tips', 'live_listings', 'faq', 'related_pages', 'cta_block'],
  'content-temporal': ['hero_intro', 'seasonal_context', 'curated_picks', 'local_tips', 'live_listings', 'faq', 'related_pages', 'cta_block'],
  'content-category': ['hero_intro', 'curated_picks', 'local_tips', 'live_listings', 'faq', 'related_pages', 'cta_block'],
  'content-location-audience': ['hero_intro', 'audience_callout', 'neighborhood_profile', 'curated_picks', 'local_tips', 'live_listings', 'faq', 'related_pages', 'cta_block'],
  'content-location-temporal': ['hero_intro', 'seasonal_context', 'neighborhood_profile', 'curated_picks', 'local_tips', 'live_listings', 'faq', 'related_pages', 'cta_block'],
  'category-location': ['hero_intro', 'neighborhood_profile', 'curated_picks', 'local_tips', 'live_listings', 'faq', 'related_pages', 'cta_block'],
  'audience-temporal': ['hero_intro', 'audience_callout', 'seasonal_context', 'curated_picks', 'local_tips', 'live_listings', 'faq', 'related_pages', 'cta_block'],
  'category-temporal': ['hero_intro', 'seasonal_context', 'curated_picks', 'local_tips', 'live_listings', 'faq', 'related_pages', 'cta_block'],
  'location-guide': ['hero_intro', 'neighborhood_profile', 'curated_picks', 'local_tips', 'live_listings', 'faq', 'related_pages', 'cta_block'],
};

/**
 * Minimum item counts per section type.
 * Generation pipeline rejects pages that don't meet these thresholds.
 */
export const SECTION_MIN_COUNTS: Record<string, number> = {
  'curated_picks.items': 6,
  'local_tips.tips': 4,
  'faq': 4,
  'related_pages': 4,
  'seo.keywords': 5,
};

/**
 * Maximum item counts per section type.
 */
export const SECTION_MAX_COUNTS: Record<string, number> = {
  'curated_picks.items': 12,
  'local_tips.tips': 8,
  'faq': 7,
  'related_pages': 8,
  'seo.keywords': 8,
};
