import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { createLogger } from '@/lib/logger';

const log = createLogger('useArticles');

export interface Article {
  id: string;
  title: string;
  slug: string;
  content: string;
  excerpt?: string;
  featured_image_url?: string;
  author_id: string;
  status: string;
  category: string;
  tags: string[];
  seo_title?: string;
  seo_description?: string;
  seo_keywords?: string[];
  view_count: number;
  published_at?: string;
  created_at: string;
  updated_at: string;
  generated_from_suggestion_id?: string;
}

export interface CreateArticleData {
  title: string;
  content: string;
  excerpt?: string;
  featured_image_url?: string;
  status?: string;
  category?: string;
  tags?: string[];
  seo_title?: string;
  seo_description?: string;
  seo_keywords?: string[];
}

export interface UpdateArticleData extends Partial<CreateArticleData> {
  id: string;
}

export const useArticles = (options?: { autoLoad?: boolean }) => {
  const [articles, setArticles] = useState<Article[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast();

  const loadArticles = async (status?: string) => {
    try {
      setLoading(true);
      let query = supabase
        .from('articles')
        .select('*')
        .order('updated_at', { ascending: false });

      if (status && status !== 'all') {
        query = query.eq('status', status);
      }
      // If status is 'all' or undefined, load all articles without filtering

      const { data, error } = await query;

      if (error) throw error;

      setArticles(data || []);
      setError(null);
    } catch (err: any) {
      log.error('loadArticles', 'Error loading articles', { error: err });
      setError(err.message);
      toast({
        title: 'Error loading articles',
        description: err.message,
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  const getArticleBySlug = async (slug: string): Promise<Article | null> => {
    try {
      const { data, error } = await supabase
        .from('articles')
        .select('*')
        .eq('slug', slug)
        .single();

      if (error) throw error;

      // Increment view count
      if (data) {
        await supabase
          .from('articles')
          .update({ view_count: data.view_count + 1 })
          .eq('id', data.id);
      }

      return data;
    } catch (err: any) {
      log.error('getArticleBySlug', 'Error getting article by slug', { error: err });
      setError(err.message);
      return null;
    }
  };

  const createArticle = async (articleData: CreateArticleData): Promise<Article | null> => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('User not authenticated');

      const { data, error } = await supabase
        .from('articles')
        .insert({
          title: articleData.title,
          slug: '', // Will be auto-generated by trigger
          content: articleData.content,
          excerpt: articleData.excerpt,
          featured_image_url: articleData.featured_image_url,
          author_id: user.id,
          status: articleData.status || 'draft',
          category: articleData.category || 'General',
          tags: articleData.tags || [],
          seo_title: articleData.seo_title,
          seo_description: articleData.seo_description,
          seo_keywords: articleData.seo_keywords || [],
        })
        .select()
        .single();

      if (error) throw error;

      toast({
        title: 'Article created',
        description: 'Your article has been created successfully.',
      });

      // Refresh articles list
      await loadArticles();

      return data;
    } catch (err: any) {
      log.error('createArticle', 'Error creating article', { error: err });
      setError(err.message);
      toast({
        title: 'Error creating article',
        description: err.message,
        variant: 'destructive',
      });
      return null;
    }
  };

  const updateArticle = async (articleData: UpdateArticleData): Promise<Article | null> => {
    try {
      const { id, ...updateData } = articleData;
      
      const { data, error } = await supabase
        .from('articles')
        .update(updateData)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;

      toast({
        title: 'Article updated',
        description: 'Your article has been updated successfully.',
      });

      // Refresh articles list
      await loadArticles();

      return data;
    } catch (err: any) {
      log.error('updateArticle', 'Error updating article', { error: err });
      setError(err.message);
      toast({
        title: 'Error updating article',
        description: err.message,
        variant: 'destructive',
      });
      return null;
    }
  };

  const deleteArticle = async (id: string): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from('articles')
        .delete()
        .eq('id', id);

      if (error) throw error;

      toast({
        title: 'Article deleted',
        description: 'The article has been deleted successfully.',
      });

      // Refresh articles list
      await loadArticles();

      return true;
    } catch (err: any) {
      log.error('deleteArticle', 'Error deleting article', { error: err });
      setError(err.message);
      toast({
        title: 'Error deleting article',
        description: err.message,
        variant: 'destructive',
      });
      return false;
    }
  };

  const publishArticle = async (id: string): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from('articles')
        .update({ 
          status: 'published',
          published_at: new Date().toISOString()
        })
        .eq('id', id);

      if (error) throw error;

      toast({
        title: 'Article published',
        description: 'Your article is now live and visible to the public.',
      });

      await loadArticles();
      return true;
    } catch (err: any) {
      log.error('publishArticle', 'Error publishing article', { error: err });
      setError(err.message);
      toast({
        title: 'Error publishing article',
        description: err.message,
        variant: 'destructive',
      });
      return false;
    }
  };

  const generateArticleFromSuggestion = async (suggestionId: string, customPrompt?: string): Promise<Article | null> => {
    try {
      setLoading(true);
      
      const { data, error } = await supabase.functions.invoke('generate-article', {
        body: { suggestionId, customPrompt }
      });

      if (error) throw error;

      if (data.success) {
        toast({
          title: 'Article generated!',
          description: 'Your article has been generated from the AI suggestion.',
        });

        await loadArticles();
        return data.article;
      } else {
        throw new Error(data.error || 'Failed to generate article');
      }
    } catch (err: any) {
      log.error('generateArticle', 'Error generating article', { error: err });
      setError(err.message);
      toast({
        title: 'Error generating article',
        description: err.message,
        variant: 'destructive',
      });
      return null;
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (options?.autoLoad !== false) {
      loadArticles();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return {
    articles,
    loading,
    error,
    loadArticles,
    getArticleBySlug,
    createArticle,
    updateArticle,
    deleteArticle,
    publishArticle,
    generateArticleFromSuggestion,
  };
};