name: DesMoinesInsider
options:
  bundleIdPrefix: com.desmoines
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  Supabase:
    url: https://github.com/supabase-community/supabase-swift
    from: "2.0.0"

targets:
  DesMoinesInsider:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: DesMoinesInsider
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: DesMoinesInsider/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.desmoines.aipulse
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    preBuildScripts:
      - name: Generate Supabase Secrets
        script: |
          # Generate Secrets.generated.swift from environment variables.
          # In CI, SUPABASE_URL and SUPABASE_ANON_KEY are set by the workflow.
          # For local development, create ios/Secrets.xcconfig or set env vars.
          if [ -f "$PROJECT_DIR/scripts/generate-secrets.sh" ]; then
            bash "$PROJECT_DIR/scripts/generate-secrets.sh"
          else
            echo "warning: generate-secrets.sh not found — using placeholder secrets"
          fi
        basedOnDependencyAnalysis: false
    dependencies:
      - package: Supabase
    entitlements:
      path: DesMoinesInsider/App/DesMoinesInsider.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default

  # ──────────────────────────────────────────────────
  # UI Test Target — Used by Fastlane Snapshot for
  # automated App Store screenshot generation.
  # ──────────────────────────────────────────────────
  DesMoinesInsiderUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: DesMoinesInsiderUITests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: DesMoinesInsiderUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.desmoines.aipulse.uitests
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        TEST_HOST: ""
        TEST_TARGET_NAME: DesMoinesInsider
    dependencies:
      - target: DesMoinesInsider

schemes:
  DesMoinesInsider:
    build:
      targets:
        DesMoinesInsider: all
    run:
      config: Debug
    profile:
      config: Release
    archive:
      config: Release

  # Scheme for running UI tests / Fastlane Snapshot
  DesMoinesInsiderUITests:
    build:
      targets:
        DesMoinesInsider: all
        DesMoinesInsiderUITests: [test]
    test:
      config: Debug
      targets:
        - DesMoinesInsiderUITests
