name: DesMoinesInsider
options:
  bundleIdPrefix: com.desmoinespulse
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  Supabase:
    url: https://github.com/supabase-community/supabase-swift
    from: "2.0.0"

targets:
  DesMoinesInsider:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: DesMoinesInsider
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: DesMoinesInsider/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.desmoinespulse.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SUPABASE_URL: $(SUPABASE_URL)
        SUPABASE_ANON_KEY: $(SUPABASE_ANON_KEY)
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    dependencies:
      - package: Supabase
    entitlements:
      path: DesMoinesInsider/App/DesMoinesInsider.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default

schemes:
  DesMoinesInsider:
    build:
      targets:
        DesMoinesInsider: all
    run:
      config: Debug
      environmentVariables:
        - variable: SUPABASE_URL
          value: "https://your-project.supabase.co"
          isEnabled: true
        - variable: SUPABASE_ANON_KEY
          value: "your-anon-key"
          isEnabled: true
    profile:
      config: Release
    archive:
      config: Release
