import { Navigate } from "react-router-dom";

/**
 * WEB-SEO-007 — /weekend is deprecated in favour of /events/this-weekend.
 *
 * Cloudflare Pages serves the 301 (public/_redirects), so a crawler or a
 * cold visit never reaches this component. It exists as the in-app backstop
 * for client-side navigation, which does not go through the edge.
 *
 * What used to render here was <WeekendGuide />, and it had to go now rather
 * than at route-removal time: fetchWeekendGuide() never queried anything. It
 * built a literal object — "This weekend in Des Moines! Check out these
 * featured events.", events_count: 5 — and the page presented it as
 * "AI-generated guide featuring 5 local events", "Generated by AI on
 * <today's date>". Fabricated content under an AI attribution byline, on a
 * public sitemapped URL. Nothing in it was worth porting to
 * EventsThisWeekend, which fetches real events.
 *
 * The route stays registered in App.tsx for at least one release cycle per
 * the Backward Compatibility rules in CLAUDE.md — public routes are
 * referenced by external links. Delete this file, the App.tsx route and
 * src/components/WeekendGuide.tsx together in the release that retires it;
 * keep the _redirects entry after that.
 */
export default function WeekendPage() {
  return <Navigate to="/events/this-weekend" replace />;
}
