#!/usr/bin/env tsx
/**
 * pSEO route-collision guard (WEB-SEO-013 AC7).
 *
 * The pSEO taxonomy generates URLs by combining dimensions. Some of those
 * combinations land on pages that already exist as hand-built, prerendered,
 * canonical routes — and publishing a templated duplicate alongside one is the
 * WEB-SEO-007 cannibalization mistake repeated at scale, except this time we
 * would be doing it several hundred times.
 *
 * This is not hypothetical: /things-to-do/tourists shipped, duplicated
 * /visitors-guide, and had to be 301'd after the fact (see public/_redirects).
 * That URL is still generated by the taxonomy, and this script still reports
 * it — which is the control proving the check works.
 *
 * RUN THIS BEFORE ANY GENERATION RUN, not once. Its answer changes whenever
 * src/pseo/taxonomy.ts gains a dimension value or src/App.tsx gains a route,
 * and both happen routinely.
 *
 * Exit code is 0 — this reports, it does not gate, because the pipeline it
 * guards is not wired up yet. Wire it into that pipeline as a hard stop when
 * generation is switched on.
 *
 * Usage: npx tsx scripts/check-pseo-collisions.ts
 */
import { readFileSync } from 'node:fs';
import { classifySlugs } from './lib/pseoRouteClaims.mjs';
import {
  contentTypeDimension,
  locationDimension,
  audienceDimension,
  temporalDimension,
  categoryDimension,
} from '../src/pseo/taxonomy';

const dims: Record<string, string[]> = {
  content_type: contentTypeDimension.values.map((v) => v.slug),
  location: locationDimension.values.map((v) => v.slug),
  audience: audienceDimension.values.map((v) => v.slug),
  temporal: temporalDimension.values.map((v) => v.slug),
  category: categoryDimension.values.map((v) => v.slug),
};

// The URL patterns, transcribed from src/pseo/pageTypes.ts.
const patterns: Array<[string, string[]]> = [
  ['/{content_type}/{location}', ['content_type', 'location']],
  ['/{content_type}/{audience}', ['content_type', 'audience']],
  ['/{content_type}/{temporal}', ['content_type', 'temporal']],
  ['/{content_type}/{category}', ['content_type', 'category']],
  ['/{content_type}/{location}/{audience}', ['content_type', 'location', 'audience']],
  ['/{content_type}/{location}/{temporal}', ['content_type', 'location', 'temporal']],
  ['/{category}/{location}', ['category', 'location']],
  ['/things-to-do/{audience}/{temporal}', ['audience', 'temporal']],
  ['/{category}/{temporal}', ['category', 'temporal']],
  ['/guide/{location}', ['location']],
];

const generated = new Map<string, string>(); // url -> pattern that produced it
for (const [label, keys] of patterns) {
  const parts = keys.map((k) => dims[k]);
  const walk = (i: number, acc: string[]) => {
    if (i === parts.length) {
      const url = label.startsWith('/things-to-do')
        ? `/things-to-do/${acc.join('/')}`
        : label.startsWith('/guide/')
          ? `/guide/${acc.join('/')}`
          : `/${acc.join('/')}`;
      if (!generated.has(url)) generated.set(url, label);
      return;
    }
    for (const v of parts[i]) walk(i + 1, [...acc, v]);
  };
  walk(0, []);
}

// Everything that already exists.
//
// ROUTE CLAIMS COME FROM THE SHARED MODULE, not from a local regex. This used to
// build its own set with
//     .filter((p) => !p.includes(':') && p !== '*')
// which DROPPED EVERY PARAMETERISED ROUTE - so /restaurants/{category} and
// /attractions/{location}, which resolve to RestaurantDetails and
// AttractionDetails rather than to a pSEO page, reported as clean. That is the
// class of collision that turned out to matter most: of the 22 URLs the
// shippable set first selected, 13 were claimed by an entity-detail route and
// would have been submitted to Google as soft-404s (WEB-SEO-013).
//
// classifySlugs is what check-pseo-route-collisions.mjs uses against PUBLISHED
// slugs. This runs the same rules over what the taxonomy COULD generate, so the
// forward-looking check and the current-state check cannot disagree about what
// "claimed" means.
const claims = classifySlugs([...generated.keys()], {
  appPath: 'src/App.tsx',
  redirectsPath: 'public/_redirects',
});

const sitemapped = new Set<string>();
for (const f of ['sitemap-static.xml']) {
  const xml = readFileSync(`public/${f}`, 'utf8');
  for (const m of xml.matchAll(/<loc>https?:\/\/[^/]+([^<]*)<\/loc>/g)) sitemapped.add(m[1].replace(/\/$/, '') || '/');
}

const patternOf = (url: string) => generated.get(url) ?? '(unknown pattern)';
const hitsRoute = claims.exact.map((e) => `${e.slug}   <- ${patternOf(e.slug)}   [${e.route}]`);
const hitsShadowed = claims.shadowed.map((e) => `${e.slug}   <- ${patternOf(e.slug)}   [${e.route}]`);
const hitsRedirect = claims.redirected.map((slug) => `${slug}   <- ${patternOf(slug)}`);
const hitsSitemap = [...generated.keys()]
  .filter((url) => !claims.claimed.has(url) && !claims.redirected.includes(url) && sitemapped.has(url))
  .map((url) => `${url}   <- ${patternOf(url)}`);

console.log(`taxonomy can generate ${generated.size} distinct URLs across ${patterns.length} patterns`);
console.log(`  content_type=${dims.content_type.length} location=${dims.location.length} audience=${dims.audience.length} temporal=${dims.temporal.length} category=${dims.category.length}\n`);

console.log(`COLLIDES WITH A LITERAL ROUTE IN App.tsx (${hitsRoute.length}) - the generated page would never render:`);
hitsRoute.sort().forEach((h) => console.log('  ' + h));

// The bigger and quieter half. An entity-detail route answers the URL and looks
// for an entity with that slug, finds none, and serves whatever it does for a
// miss - which per WEB-SEO-006 is the SPA shell. Nothing errors.
console.log(`
SHADOWED BY A PARAMETERISED ROUTE (${hitsShadowed.length}) - resolves to an entity page, not a pSEO page:`);
// Grouped by route. 257 lines of slugs is not a finding; "257 generatable URLs
// sit under three entity-detail routes" is the same shape the published-side
// check already reports, and the same decision: which layer owns the prefix.
{
  const byRoute = new Map<string, string[]>();
  for (const { slug, route } of claims.shadowed) {
    if (!byRoute.has(route)) byRoute.set(route, []);
    byRoute.get(route)!.push(slug);
  }
  for (const [route, list] of [...byRoute].sort((a, b) => b[1].length - a[1].length)) {
    console.log(`  ${route.padEnd(24)} ${String(list.length).padStart(4)}   e.g. ${list.slice(0, 3).join(', ')}`);
  }
  console.log(
    '\n  Nothing errors on these: the entity route looks for a slug it will not find and\n' +
      '  serves whatever it does for a miss, which per WEB-SEO-006 is the SPA shell. Decide\n' +
      '  per prefix which layer owns the slug before generating any of them.',
  );
}
console.log(`\nCOLLIDES WITH AN EXISTING _redirects RULE (${hitsRedirect.length}):`);
hitsRedirect.sort().forEach((h) => console.log('  ' + h));
console.log(`\nCOLLIDES WITH A SITEMAPPED STATIC URL (${hitsSitemap.length}):`);
hitsSitemap.sort().forEach((h) => console.log('  ' + h));
