#!/usr/bin/env tsx
/**
 * pSEO route-collision guard (WEB-SEO-013 AC7).
 *
 * The pSEO taxonomy generates URLs by combining dimensions. Some of those
 * combinations land on pages that already exist as hand-built, prerendered,
 * canonical routes — and publishing a templated duplicate alongside one is the
 * WEB-SEO-007 cannibalization mistake repeated at scale, except this time we
 * would be doing it several hundred times.
 *
 * This is not hypothetical: /things-to-do/tourists shipped, duplicated
 * /visitors-guide, and had to be 301'd after the fact (see public/_redirects).
 * That URL is still generated by the taxonomy, and this script still reports
 * it — which is the control proving the check works.
 *
 * RUN THIS BEFORE ANY GENERATION RUN, not once. Its answer changes whenever
 * src/pseo/taxonomy.ts gains a dimension value or src/App.tsx gains a route,
 * and both happen routinely.
 *
 * Exit code is 0 — this reports, it does not gate, because the pipeline it
 * guards is not wired up yet. Wire it into that pipeline as a hard stop when
 * generation is switched on.
 *
 * Usage: npx tsx scripts/check-pseo-collisions.ts
 */
import { readFileSync } from 'node:fs';
import {
  contentTypeDimension,
  locationDimension,
  audienceDimension,
  temporalDimension,
  categoryDimension,
} from '../src/pseo/taxonomy';

const dims: Record<string, string[]> = {
  content_type: contentTypeDimension.values.map((v) => v.slug),
  location: locationDimension.values.map((v) => v.slug),
  audience: audienceDimension.values.map((v) => v.slug),
  temporal: temporalDimension.values.map((v) => v.slug),
  category: categoryDimension.values.map((v) => v.slug),
};

// The URL patterns, transcribed from src/pseo/pageTypes.ts.
const patterns: Array<[string, string[]]> = [
  ['/{content_type}/{location}', ['content_type', 'location']],
  ['/{content_type}/{audience}', ['content_type', 'audience']],
  ['/{content_type}/{temporal}', ['content_type', 'temporal']],
  ['/{content_type}/{category}', ['content_type', 'category']],
  ['/{content_type}/{location}/{audience}', ['content_type', 'location', 'audience']],
  ['/{content_type}/{location}/{temporal}', ['content_type', 'location', 'temporal']],
  ['/{category}/{location}', ['category', 'location']],
  ['/things-to-do/{audience}/{temporal}', ['audience', 'temporal']],
  ['/{category}/{temporal}', ['category', 'temporal']],
  ['/guide/{location}', ['location']],
];

const generated = new Map<string, string>(); // url -> pattern that produced it
for (const [label, keys] of patterns) {
  const parts = keys.map((k) => dims[k]);
  const walk = (i: number, acc: string[]) => {
    if (i === parts.length) {
      const url = label.startsWith('/things-to-do')
        ? `/things-to-do/${acc.join('/')}`
        : label.startsWith('/guide/')
          ? `/guide/${acc.join('/')}`
          : `/${acc.join('/')}`;
      if (!generated.has(url)) generated.set(url, label);
      return;
    }
    for (const v of parts[i]) walk(i + 1, [...acc, v]);
  };
  walk(0, []);
}

// Everything that already exists.
const app = readFileSync('src/App.tsx', 'utf8');
const realRoutes = new Set(
  [...app.matchAll(/<Route\s+path="([^"]+)"/g)].map((m) => m[1]).filter((p) => !p.includes(':') && p !== '*')
);
const redirects = new Set(
  readFileSync('public/_redirects', 'utf8')
    .split(/\r?\n/)
    .filter((l) => l.trim() && !l.trim().startsWith('#'))
    .map((l) => l.trim().split(/\s+/)[0])
);
const sitemapped = new Set<string>();
for (const f of ['sitemap-static.xml']) {
  const xml = readFileSync(`public/${f}`, 'utf8');
  for (const m of xml.matchAll(/<loc>https?:\/\/[^/]+([^<]*)<\/loc>/g)) sitemapped.add(m[1].replace(/\/$/, '') || '/');
}

const hitsRoute: string[] = [];
const hitsRedirect: string[] = [];
const hitsSitemap: string[] = [];
for (const [url, pattern] of generated) {
  if (realRoutes.has(url)) hitsRoute.push(`${url}   <- ${pattern}`);
  else if (redirects.has(url)) hitsRedirect.push(`${url}   <- ${pattern}`);
  else if (sitemapped.has(url)) hitsSitemap.push(`${url}   <- ${pattern}`);
}

console.log(`taxonomy can generate ${generated.size} distinct URLs across ${patterns.length} patterns`);
console.log(`  content_type=${dims.content_type.length} location=${dims.location.length} audience=${dims.audience.length} temporal=${dims.temporal.length} category=${dims.category.length}\n`);

console.log(`COLLIDES WITH A REAL ROUTE IN App.tsx (${hitsRoute.length}) — these would be shadowed or would shadow:`);
hitsRoute.sort().forEach((h) => console.log('  ' + h));
console.log(`\nCOLLIDES WITH AN EXISTING _redirects RULE (${hitsRedirect.length}):`);
hitsRedirect.sort().forEach((h) => console.log('  ' + h));
console.log(`\nCOLLIDES WITH A SITEMAPPED STATIC URL (${hitsSitemap.length}):`);
hitsSitemap.sort().forEach((h) => console.log('  ' + h));
