#!/usr/bin/env tsx
/**
 * SEO-064 - measure every published page src/pseo/duplicateRule.ts governs
 * (audience x time, restaurant cuisine x time) against its parent's listing,
 * join Search Console impressions, and write the table plus the SQL that
 * applies the verdicts. It never writes to the database itself.
 *
 *   npx tsx scripts/measure-pseo-duplicates.ts --csv <Pages.csv> --out docs/seo/x.csv [--sql out.sql]
 *
 * SQL per verdict:
 *   indexable           nothing
 *   noindex-canonical   seo.robots = "noindex, follow", seo.canonicalUrl = parent page
 *   redirect            is_published = false; the 301 goes in public/_redirects
 *                       by hand (on both branches), printed as a comment
 *
 * Reads production with the anon key (VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY
 * from the environment or .env).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';
import { MAX_PARENT_OVERLAP, MIN_DISTINCT_ITEMS } from '../src/pseo/duplicateRule';
import { measureDuplicates, readGscPages, readRedirects, readSitemapPaths, verdictFor, type DuplicatePageRow } from './lib/pseoDuplicates';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function env(name: string): string | undefined {
  if (process.env[name]) return process.env[name];
  try {
    for (const line of readFileSync(path.join(ROOT, '.env'), 'utf8').split(/\r?\n/)) {
      const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
      if (m && m[1] === name) return m[2].replace(/^['"]|['"]$/g, '');
    }
  } catch {
    // environment only
  }
  return undefined;
}

const arg = (name: string) => {
  const i = process.argv.indexOf(name);
  return i > 0 ? process.argv[i + 1] : undefined;
};

const base = env('VITE_SUPABASE_URL');
const key = env('VITE_SUPABASE_ANON_KEY');
const csv = arg('--csv');
const outCsv = arg('--out');
const outSql = arg('--sql');
if (!base || !key || !csv || !outCsv) {
  console.error('usage: measure-pseo-duplicates.ts --csv <Pages.csv> --out <table.csv> [--sql <out.sql>] (needs VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY)');
  process.exit(2);
}

const res = await fetch(
  `${base.replace(/\/+$/, '')}/rest/v1/pseo_pages?select=slug,page_type_id,dimensions,seo,is_published&is_published=eq.true&order=slug&limit=1000`,
  { headers: { apikey: key, Authorization: `Bearer ${key}` } },
);
if (!res.ok) throw new Error(`pseo_pages: HTTP ${res.status}`);
const pages = (await res.json()) as DuplicatePageRow[];
const bySlug = new Map(pages.map((p) => [p.slug, p]));
const redirects = readRedirects(ROOT);
const gsc = readGscPages(csv);
const now = new Date();
const rows = await measureDuplicates({ base, key }, pages, redirects, readSitemapPaths(ROOT), now);

const q = (s: string | number) => (typeof s === 'number' ? String(s) : /[",]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s);
const header = [
  'slug', 'family', 'parent_listing', 'target', 'child_items', 'parent_items', 'shared', 'overlap_pct',
  'gsc_impressions_3mo', 'gsc_clicks_3mo', 'verdict', 'previous_robots', 'measured_at',
];
const lines = [header.join(',')];
const sql = [
  `-- SEO-064 duplicate rule (overlap < ${MAX_PARENT_OVERLAP * 100}% and >= ${MIN_DISTINCT_ITEMS} items to stay indexable).`,
  '-- Generated by scripts/measure-pseo-duplicates.ts',
  'begin;',
];
const counts: Record<string, number> = { indexable: 0, 'noindex-canonical': 0, redirect: 0 };
for (const r of rows) {
  const g = gsc.get(r.slug.toLowerCase()) ?? { clicks: 0, impressions: 0 };
  const verdict = verdictFor(r, g.impressions);
  counts[verdict]++;
  lines.push(
    [
      r.slug, r.family, r.parentListing, r.target, r.childItems, r.parentItems, r.shared, Math.round(r.overlap * 100),
      g.impressions, g.clicks, verdict, bySlug.get(r.slug)?.seo?.robots ?? '', now.toISOString().slice(0, 10),
    ].map(q).join(','),
  );
  const s = r.slug.replace(/'/g, "''");
  if (verdict === 'noindex-canonical') {
    const patch = JSON.stringify({ robots: 'noindex, follow', canonicalUrl: r.target }).replace(/'/g, "''");
    sql.push(`update pseo_pages set seo = seo || '${patch}'::jsonb, updated_at = now() where slug = '${s}'; -- ${g.impressions} impr`);
  } else if (verdict === 'redirect') {
    sql.push(`update pseo_pages set is_published = false, updated_at = now() where slug = '${s}'; -- 301 to ${r.target}`);
  }
}
sql.push('commit;');
writeFileSync(path.resolve(outCsv), `${lines.join('\n')}\n`);
if (outSql) writeFileSync(path.resolve(outSql), `${sql.join('\n')}\n`);
console.log(
  `[measure-pseo-duplicates] ${rows.length} governed page(s): ${counts.indexable} indexable, ` +
    `${counts['noindex-canonical']} noindex+canonical, ${counts.redirect} redirect. Table: ${outCsv}` +
    (outSql ? `; SQL: ${outSql}` : ''),
);
