#!/usr/bin/env tsx
/**
 * SEO-056 - rewrite the time-relative pSEO pages (today, this weekend, a month,
 * a season) with evergreen copy from src/pseo/timeRelative.ts, as SQL for
 * review. It never writes to the database itself.
 *
 *   npx tsx scripts/write-pseo-time-relative-pages.ts > time-relative.sql
 *   (back up the rows it names, then apply with psql)
 *
 * Per published time-relative row it emits one UPDATE replacing seo (title,
 * h1, description, keywords; canonicalUrl, ogType and robots are kept),
 * sections, structured_data and generation_meta. The new sections are an
 * intro that describes how the list is selected, the live listing, and an
 * FAQ about the list - no event, venue, date, price or dish, because the
 * pages were written in March and named St. Patrick's Day parades on a
 * "today" page read in October.
 *
 * Rows in HUB_DUPLICATES are unpublished instead (their 301s live in
 * public/_redirects).
 *
 * PseoPage renders the same builder at runtime, so the rows and the HTML
 * agree; the rewrite is what keeps the stored data, the FAQ schema and
 * scripts/check-pseo-time-copy.ts honest.
 *
 * Reads production with the anon key (VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY
 * from the environment or .env).
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';
import { buildTimeRelativePage, HUB_DUPLICATES, isTimeRelative, TIME_TEMPLATE_GENERATOR } from '../src/pseo/timeRelative';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export interface TimeRow {
  slug: string;
  dimensions: Array<{ dimension: string; slug: string; name: string; tier?: number }>;
  seo: Record<string, unknown> | null;
  is_published: boolean;
}

function env(): Record<string, string | undefined> {
  const out: Record<string, string | undefined> = { ...process.env };
  try {
    for (const line of readFileSync(path.join(ROOT, '.env'), 'utf8').split(/\r?\n/)) {
      const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
      if (m && out[m[1]] === undefined) out[m[1]] = m[2].replace(/^['"]|['"]$/g, '');
    }
  } catch {
    // environment only
  }
  return out;
}

const lit = (v: unknown) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const str = (v: string) => `'${v.replace(/'/g, "''")}'`;

/** The SQL for one row, or null when the row is not time-relative. Pure, for the test. */
export function statementFor(row: TimeRow, generatedAt: string): string | null {
  if (!row.is_published || !isTimeRelative(row)) return null;
  if (HUB_DUPLICATES[row.slug]) {
    return `update pseo_pages set is_published = false, updated_at = now() where slug = ${str(row.slug)}; -- 301 to ${HUB_DUPLICATES[row.slug]}`;
  }
  const built = buildTimeRelativePage(row.dimensions);
  if (!built) return `-- skipped ${row.slug}: slug reads as time-relative but its dimensions name no window`;
  const keep = row.seo ?? {};
  const seo = {
    ...(keep.canonicalUrl ? { canonicalUrl: keep.canonicalUrl } : { canonicalUrl: row.slug }),
    ogType: keep.ogType ?? 'website',
    ...(keep.robots ? { robots: keep.robots } : {}),
    ...built.seo,
  };
  const structured = {
    '@type': 'WebPage',
    breadcrumb: [...built.breadcrumb, { name: built.seo.h1, url: row.slug }],
    faqItems: built.faqs,
  };
  const meta = {
    generatedAt,
    generatedBy: TIME_TEMPLATE_GENERATOR,
    promptVersion: 'none',
    modelUsed: 'none',
    wordCount: JSON.stringify(built.sections).split(/\s+/).length,
    sourceTable: built.entity,
  };
  return (
    `update pseo_pages set seo = ${lit(seo)}, sections = ${lit(built.sections)}, structured_data = ${lit(structured)}, ` +
    `generation_meta = ${lit(meta)}, updated_at = now() where slug = ${str(row.slug)};`
  );
}

async function main() {
  const E = env();
  const base = E.VITE_SUPABASE_URL;
  const key = E.VITE_SUPABASE_ANON_KEY;
  if (!base || !key) throw new Error('VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are required.');
  const res = await fetch(
    `${base.replace(/\/+$/, '')}/rest/v1/pseo_pages?select=slug,dimensions,seo,is_published&is_published=eq.true&order=slug&limit=1000`,
    { headers: { apikey: key, Authorization: `Bearer ${key}` } },
  );
  if (!res.ok) throw new Error(`pseo_pages: HTTP ${res.status}`);
  const rows = (await res.json()) as TimeRow[];
  if (rows.length === 0) throw new Error('pseo_pages returned no published rows; refusing to emit an empty script.');
  const generatedAt = new Date().toISOString();
  const out = ['-- SEO-056 time-relative pSEO pages. Generated by scripts/write-pseo-time-relative-pages.ts', 'begin;'];
  let n = 0;
  for (const row of rows) {
    const sql = statementFor(row, generatedAt);
    if (sql) {
      out.push(sql);
      n++;
    }
  }
  out.push('commit;');
  out.splice(1, 0, `-- ${n} statement(s) over ${rows.length} published rows`);
  process.stdout.write(`${out.join('\n')}\n`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  main().catch((err) => {
    console.error(`[write-pseo-time-relative-pages] ${(err as Error).message}`);
    process.exit(1);
  });
}
