// Secrets.generated.swift
// AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-secrets.sh
// This file is gitignored and must never be committed.
//
// To populate with real values, run:
//   SUPABASE_URL="https://your-project.supabase.co" SUPABASE_ANON_KEY="your-key" ./scripts/generate-secrets.sh
//
// Or copy Secrets.xcconfig.example to Secrets.xcconfig and fill in values.

import Foundation

/// Build-time injected secrets. Generated from environment variables or Secrets.xcconfig.
enum GeneratedSecrets {
    static let supabaseURL = ""
    static let supabaseAnonKey = ""
}
