-- Comprehensive hotel seed data for the Des Moines metro area
-- Replaces the initial 12-hotel seed with 60+ hotels across all areas
-- Includes brand_parent for affiliate program mapping

-- Clear existing seed data
DELETE FROM public.event_hotels;
DELETE FROM public.hotels;

INSERT INTO public.hotels (name, slug, short_description, description, address, city, state, zip, area, phone, website, star_rating, price_range, avg_nightly_rate, hotel_type, chain_name, brand_parent, amenities, is_featured, is_active, check_in_time, check_out_time) VALUES

-- =====================================================
-- DOWNTOWN DES MOINES
-- =====================================================
(
  'Hilton Des Moines Downtown',
  'hilton-des-moines-downtown',
  'Full-service Hilton in the heart of downtown, connected to the skywalk system.',
  'Located in the center of downtown Des Moines, the Hilton Des Moines Downtown offers easy access to the Iowa Events Center, Wells Fargo Arena, and the Des Moines Civic Center via the skywalk system. The hotel features modern rooms, an on-site restaurant, indoor pool, and fitness center.',
  '435 Park St',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 241-1456',
  'https://www.hilton.com/en/hotels/dsmhihf-hilton-des-moines-downtown/',
  4.0, '$$$', 169, 'Hotel', 'Hilton', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Business Center', 'Free Parking'],
  true, true, '3:00 PM', '12:00 PM'
),
(
  'Des Moines Marriott Downtown',
  'des-moines-marriott-downtown',
  'Upscale Marriott property steps from the Capitol and Court Avenue.',
  'The Des Moines Marriott Downtown is a premier hotel offering upscale accommodations in the heart of the city. Walking distance to the Iowa State Capitol, Court Avenue Entertainment District, and connected to the skywalk. Features include a rooftop bar, indoor pool, and full fitness center.',
  '700 Grand Ave',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 245-5500',
  'https://www.marriott.com/hotels/travel/dsmia-des-moines-marriott-downtown/',
  4.0, '$$$', 179, 'Hotel', 'Marriott', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Business Center', 'Suite Available'],
  true, true, '4:00 PM', '11:00 AM'
),
(
  'Embassy Suites by Hilton Des Moines Downtown',
  'embassy-suites-des-moines-downtown',
  'All-suite hotel with complimentary breakfast and evening reception downtown.',
  'The Embassy Suites by Hilton Des Moines Downtown features spacious two-room suites with a separate living area. Enjoy complimentary cooked-to-order breakfast and an evening reception with drinks and snacks. Connected to the skywalk system and steps from the Iowa Events Center.',
  '101 E Locust St',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 244-1700',
  'https://www.hilton.com/en/hotels/dsmdnes-embassy-suites-des-moines-downtown/',
  3.5, '$$$', 169, 'Hotel', 'Embassy Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Bar/Lounge', 'Business Center', 'Suite Available'],
  true, true, '3:00 PM', '12:00 PM'
),
(
  'Renaissance Des Moines Savery Hotel',
  'renaissance-savery-hotel',
  'Historic Renaissance hotel blending 1919 elegance with modern luxury.',
  'The Renaissance Des Moines Savery Hotel is a beautifully restored historic landmark originally built in 1919. This Marriott property blends classic architecture with contemporary amenities, featuring elegant rooms, an on-site restaurant, and event spaces in the heart of downtown.',
  '401 Locust St',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 244-2151',
  'https://www.marriott.com/hotels/travel/dsmrn-renaissance-des-moines-savery-hotel/',
  3.5, '$$$', 159, 'Hotel', 'Renaissance', 'Marriott',
  ARRAY['Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Business Center', 'Suite Available'],
  true, true, '3:00 PM', '12:00 PM'
),
(
  'Hotel Fort Des Moines, Curio Collection by Hilton',
  'hotel-fort-des-moines',
  'Historic boutique hotel with modern luxury in downtown Des Moines.',
  'Originally built in 1919, Hotel Fort Des Moines is a beautifully restored historic landmark now part of Hilton''s Curio Collection. Located in the heart of downtown, it offers a unique boutique experience with spacious rooms, an on-site restaurant, and elegant event spaces.',
  '1000 Walnut St',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 243-1161',
  'https://www.hilton.com/en/hotels/dsmftqq-hotel-fort-des-moines/',
  4.0, '$$$', 159, 'Boutique Hotel', 'Curio Collection', 'Hilton',
  ARRAY['Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Business Center', 'Suite Available'],
  true, true, '3:00 PM', '11:00 AM'
),
(
  'Surety Hotel, Autograph Collection',
  'surety-hotel',
  'Boutique hotel in a beautifully restored 1913 building in downtown Des Moines.',
  'Surety Hotel is part of Marriott''s Autograph Collection, housed in a stunning 1913 building in downtown Des Moines. It features thoughtfully designed rooms, the acclaimed Mulberry Street Tavern restaurant, and a rooftop patio. Perfect for travelers seeking a unique, design-forward experience.',
  '206 6th Ave',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 985-1171',
  'https://www.marriott.com/hotels/travel/dsmar-surety-hotel-des-moines-autograph-collection/',
  4.5, '$$$$', 219, 'Boutique Hotel', 'Autograph Collection', 'Marriott',
  ARRAY['Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Suite Available'],
  true, true, '3:00 PM', '11:00 AM'
),
(
  'AC Hotel by Marriott Des Moines East Village',
  'ac-hotel-des-moines-east-village',
  'Modern Marriott lifestyle hotel in the vibrant East Village neighborhood.',
  'The AC Hotel by Marriott in the East Village offers a sleek, European-inspired design in one of Des Moines'' most walkable neighborhoods. Steps from local boutiques, restaurants, and the Des Moines Farmers'' Market. Features a rooftop bar with skyline views.',
  '401 E Grand Ave',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 518-5560',
  'https://www.marriott.com/hotels/travel/dsmac-ac-hotel-des-moines-east-village/',
  4.0, '$$$', 189, 'Boutique Hotel', 'AC Hotel', 'Marriott',
  ARRAY['Fitness Center', 'Bar/Lounge', 'Business Center'],
  true, true, '3:00 PM', '12:00 PM'
),
(
  'Hyatt Place Des Moines Downtown',
  'hyatt-place-des-moines-downtown',
  'Modern Hyatt with free breakfast and pool in downtown Des Moines.',
  'Hyatt Place Des Moines Downtown offers a contemporary stay with complimentary breakfast, indoor pool, and fitness center. Connected to the skywalk system and walking distance to Iowa Events Center, Court Avenue, and the East Village.',
  '418 6th Ave',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 282-5000',
  'https://www.hyatt.com/hyatt-place/en-US/dsmzd-hyatt-place-des-moines-downtown',
  3.0, '$$', 139, 'Hotel', 'Hyatt Place', 'Hyatt',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Hampton Inn & Suites Des Moines Downtown',
  'hampton-inn-suites-des-moines-downtown',
  'Comfortable Hampton in the heart of downtown with free hot breakfast.',
  'The Hampton Inn & Suites Des Moines Downtown provides comfortable accommodations with complimentary hot breakfast, indoor pool, and fitness center. Great location for business and leisure travelers exploring downtown Des Moines.',
  '120 SW Water St',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 288-0404',
  'https://www.hilton.com/en/hotels/dsmwshx-hampton-suites-des-moines-downtown/',
  3.0, '$$', 139, 'Hotel', 'Hampton Inn & Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Residence Inn Des Moines Downtown',
  'residence-inn-des-moines-downtown',
  'All-suite extended stay hotel with full kitchens downtown.',
  'The Residence Inn Des Moines Downtown offers spacious suites with fully equipped kitchens, ideal for extended stays. Enjoy complimentary breakfast, indoor pool, and a prime downtown location near the Iowa State Capitol and Court Avenue.',
  '100 SW Water St',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 288-0073',
  'https://www.marriott.com/hotels/travel/dsmri-residence-inn-des-moines-downtown/',
  3.0, '$$', 149, 'Extended Stay', 'Residence Inn', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Suite Available', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Staybridge Suites Des Moines Downtown',
  'staybridge-suites-des-moines-downtown',
  'Extended stay suites with full kitchens in downtown Des Moines.',
  'Staybridge Suites Des Moines Downtown offers spacious suites with full kitchens for extended stays. Enjoy complimentary breakfast, evening social receptions, and a convenient downtown location near the Iowa Events Center.',
  '201 E Locust St',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 280-3888',
  'https://www.ihg.com/staybridge/hotels/us/en/des-moines/dsmdt/hoteldetail',
  3.0, '$$', 129, 'Extended Stay', 'Staybridge Suites', 'IHG',
  ARRAY['Fitness Center', 'Free Breakfast', 'Suite Available', 'Pet Friendly', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Des Lux Hotel',
  'des-lux-hotel',
  'Upscale independent boutique hotel in downtown Des Moines.',
  'Des Lux Hotel is an upscale, independently owned boutique property offering a distinctive experience in downtown Des Moines. Features elegantly appointed rooms, personalized service, and a refined atmosphere for discerning travelers.',
  '800 Locust St',
  'Des Moines', 'IA', '50309',
  'Downtown',
  '(515) 288-5800',
  'https://www.desluxhotel.com/',
  4.0, '$$$', 179, 'Boutique Hotel', NULL, 'Independent',
  ARRAY['Fitness Center', 'Bar/Lounge', 'Suite Available', 'Business Center'],
  false, true, '3:00 PM', '11:00 AM'
),

-- =====================================================
-- DES MOINES - AIRPORT AREA
-- =====================================================
(
  'Holiday Inn Des Moines - Airport',
  'holiday-inn-des-moines-airport',
  'Convenient airport hotel with free shuttle and easy highway access.',
  'The Holiday Inn Des Moines Airport offers a convenient stay for travelers flying into Des Moines International Airport. Features include a complimentary airport shuttle, indoor pool, on-site restaurant, and easy access to I-80 and I-35.',
  '6111 Fleur Dr',
  'Des Moines', 'IA', '50321',
  'Airport',
  '(515) 287-2400',
  'https://www.ihg.com/holidayinn/hotels/us/en/des-moines/dsmap/hoteldetail',
  3.0, '$$', 109, 'Hotel', 'Holiday Inn', 'IHG',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Free Parking', 'Airport Shuttle', 'Business Center'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Hilton Garden Inn Des Moines Airport',
  'hilton-garden-inn-des-moines-airport',
  'Modern Hilton Garden Inn near the Des Moines airport with dining on-site.',
  'The Hilton Garden Inn Des Moines Airport offers comfortable accommodations near the airport with an on-site restaurant, indoor pool, and fitness center. Complimentary airport shuttle and easy highway access make it ideal for travelers.',
  '6800 Fleur Dr',
  'Des Moines', 'IA', '50321',
  'Airport',
  '(515) 285-8100',
  'https://www.hilton.com/en/hotels/dsmfigi-hilton-garden-inn-des-moines-airport/',
  3.0, '$$', 119, 'Hotel', 'Hilton Garden Inn', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Free Parking', 'Airport Shuttle', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Hampton Inn Des Moines Airport',
  'hampton-inn-des-moines-airport',
  'Value-friendly Hampton near the Des Moines airport with free breakfast.',
  'The Hampton Inn Des Moines Airport offers affordable accommodations with complimentary hot breakfast, outdoor pool, and fitness center. Free airport shuttle and convenient highway access.',
  '5001 Fleur Dr',
  'Des Moines', 'IA', '50321',
  'Airport',
  '(515) 287-7300',
  'https://www.hilton.com/en/hotels/dsmaphx-hampton-des-moines-airport/',
  2.5, '$$', 99, 'Hotel', 'Hampton Inn', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Airport Shuttle'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Homewood Suites by Hilton Des Moines Airport',
  'homewood-suites-des-moines-airport',
  'All-suite extended stay near the Des Moines airport.',
  'The Homewood Suites by Hilton Des Moines Airport offers spacious all-suite accommodations with full kitchens, ideal for extended stays. Includes complimentary breakfast, indoor pool, and airport shuttle service.',
  '7201 SW 22nd St',
  'Des Moines', 'IA', '50321',
  'Airport',
  '(515) 256-1640',
  'https://www.hilton.com/en/hotels/dsmaphw-homewood-suites-des-moines-airport/',
  3.0, '$$', 119, 'Extended Stay', 'Homewood Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Airport Shuttle', 'Suite Available', 'Pet Friendly'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Fairfield Inn & Suites Des Moines Airport',
  'fairfield-inn-des-moines-airport',
  'Affordable Marriott hotel near the Des Moines airport.',
  'The Fairfield Inn & Suites Des Moines Airport provides comfortable, affordable accommodations with complimentary breakfast, free airport shuttle, and convenient access to downtown Des Moines and major highways.',
  '6880 Fleur Dr',
  'Des Moines', 'IA', '50321',
  'Airport',
  '(515) 287-6060',
  'https://www.marriott.com/hotels/travel/dsmfi-fairfield-inn-and-suites-des-moines-airport/',
  2.5, '$$', 99, 'Hotel', 'Fairfield Inn & Suites', 'Marriott',
  ARRAY['Fitness Center', 'Free Breakfast', 'Free Parking', 'Airport Shuttle', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Quality Inn & Suites Des Moines Airport',
  'quality-inn-des-moines-airport',
  'Budget-friendly hotel near the Des Moines airport with pool.',
  'The Quality Inn & Suites Des Moines Airport offers budget-friendly accommodations with an indoor pool, complimentary breakfast, airport shuttle, and free parking. A solid value option near the airport.',
  '5231 Fleur Dr',
  'Des Moines', 'IA', '50321',
  'Airport',
  '(515) 287-3434',
  'https://www.choicehotels.com/iowa/des-moines/quality-inn-hotels/ia198',
  2.0, '$', 79, 'Hotel', 'Quality Inn', 'Choice',
  ARRAY['Pool', 'Free Breakfast', 'Free Parking', 'Airport Shuttle', 'Pet Friendly'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Baymont by Wyndham Des Moines Airport',
  'baymont-des-moines-airport',
  'Affordable Wyndham property near the Des Moines airport.',
  'Baymont by Wyndham Des Moines Airport offers budget-friendly accommodations with fitness center, free parking, and airport shuttle service. Convenient access to I-80 and I-35.',
  '6221 Willow Creek Ave',
  'Des Moines', 'IA', '50321',
  'Airport',
  '(515) 287-6464',
  'https://www.wyndhamhotels.com/baymont/des-moines-iowa/baymont-des-moines-airport/overview',
  2.0, '$', 69, 'Hotel', 'Baymont', 'Wyndham',
  ARRAY['Fitness Center', 'Free Parking', 'Airport Shuttle'],
  false, true, '3:00 PM', '11:00 AM'
),

-- =====================================================
-- WEST DES MOINES (Jordan Creek / I-80 Corridor)
-- =====================================================
(
  'West Des Moines Marriott',
  'west-des-moines-marriott',
  'Full-service Marriott near Jordan Creek Town Center.',
  'The West Des Moines Marriott offers full-service accommodations near Jordan Creek Town Center with an on-site restaurant, indoor pool, and fitness center. Convenient location for shopping, dining, and business meetings.',
  '1250 Jordan Creek Pkwy',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 267-1500',
  'https://www.marriott.com/hotels/travel/dsmwd-west-des-moines-marriott/',
  3.5, '$$$', 159, 'Hotel', 'Marriott', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Business Center', 'Suite Available'],
  false, true, '4:00 PM', '11:00 AM'
),
(
  'Hilton Garden Inn West Des Moines',
  'hilton-garden-inn-west-des-moines',
  'Comfortable Hilton property near Jordan Creek and I-80/I-35.',
  'The Hilton Garden Inn West Des Moines is ideally located near Jordan Creek Town Center, offering easy access to shopping, dining, and entertainment. Features include an indoor pool, fitness center, on-site restaurant, and complimentary parking.',
  '205 S 64th St',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 225-2000',
  'https://www.hilton.com/en/hotels/dsmwdgi-hilton-garden-inn-west-des-moines/',
  3.0, '$$', 129, 'Hotel', 'Hilton Garden Inn', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Restaurant On-Site', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Hyatt Place West Des Moines Jordan Creek',
  'hyatt-place-west-des-moines',
  'Modern Hyatt Place near Jordan Creek with free breakfast and pool.',
  'Hyatt Place West Des Moines/Jordan Creek offers a modern stay with complimentary breakfast, indoor pool, and fitness center. Steps from Jordan Creek Town Center shopping and dining. Pet-friendly accommodations available.',
  '295 S 64th St',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 267-1200',
  'https://www.hyatt.com/hyatt-place/en-US/dsmzw-hyatt-place-west-des-moines-jordan-creek',
  3.0, '$$', 129, 'Hotel', 'Hyatt Place', 'Hyatt',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Pet Friendly', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Hampton Inn & Suites West Des Moines Jordan Creek',
  'hampton-inn-west-des-moines-jordan-creek',
  'Family-friendly Hampton near Jordan Creek with free breakfast.',
  'The Hampton Inn & Suites West Des Moines/Jordan Creek features complimentary hot breakfast, indoor pool with whirlpool, and fitness center. Walking distance to Jordan Creek Town Center shopping and restaurants.',
  '6160 Mills Civic Pkwy',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 440-9400',
  'https://www.hilton.com/en/hotels/dsmwdhx-hampton-suites-west-des-moines-jordan-creek/',
  3.0, '$$', 129, 'Hotel', 'Hampton Inn & Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Homewood Suites by Hilton West Des Moines',
  'homewood-suites-west-des-moines',
  'All-suite extended stay hotel with full kitchens in West Des Moines.',
  'The Homewood Suites by Hilton West Des Moines offers spacious suites with full kitchens, complimentary breakfast, and evening social reception. Indoor pool and fitness center available. Near Valley West Mall and Jordan Creek.',
  '6220 Stagecoach Dr',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 222-9790',
  'https://www.hilton.com/en/hotels/dsmhwhw-homewood-suites-west-des-moines/',
  3.0, '$$', 129, 'Extended Stay', 'Homewood Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Suite Available', 'Pet Friendly'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Courtyard by Marriott West Des Moines Jordan Creek',
  'courtyard-west-des-moines-jordan-creek',
  'Reliable Marriott hotel near Jordan Creek Town Center.',
  'The Courtyard by Marriott West Des Moines/Jordan Creek offers a convenient location near shopping and dining. Features The Bistro restaurant, indoor pool, fitness center, and flexible meeting space.',
  '410 S 68th St',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 223-9600',
  'https://www.marriott.com/hotels/travel/dsmcy-courtyard-des-moines-west-des-moines/',
  3.0, '$$', 129, 'Hotel', 'Courtyard', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Residence Inn Des Moines West at Jordan Creek',
  'residence-inn-west-des-moines-jordan-creek',
  'All-suite extended stay near Jordan Creek Town Center.',
  'The Residence Inn West Des Moines at Jordan Creek Town Center offers spacious suites with full kitchens, complimentary breakfast, and indoor pool. Ideal for extended stays near shopping, dining, and corporate offices.',
  '160 S Jordan Creek Pkwy',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 267-0033',
  'https://www.marriott.com/hotels/travel/dsmrw-residence-inn-des-moines-west-at-jordan-creek-town-center/',
  3.0, '$$', 139, 'Extended Stay', 'Residence Inn', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Suite Available', 'Pet Friendly'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'TownePlace Suites Des Moines West Jordan Creek',
  'towneplace-suites-west-des-moines',
  'Extended stay suites with kitchens near Jordan Creek.',
  'TownePlace Suites West Des Moines/Jordan Creek offers affordable extended-stay suites with fully equipped kitchens. Free breakfast, indoor pool, and fitness center included. Near Jordan Creek Town Center.',
  '125 S 68th St',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 223-8700',
  'https://www.marriott.com/hotels/travel/dsmts-towneplace-suites-des-moines-west-jordan-creek/',
  2.5, '$$', 109, 'Extended Stay', 'TownePlace Suites', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Suite Available', 'Pet Friendly'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'SpringHill Suites Des Moines West',
  'springhill-suites-des-moines-west',
  'All-suite Marriott property near Jordan Creek Town Center.',
  'SpringHill Suites Des Moines West offers all-suite accommodations with complimentary breakfast, indoor pool, and fitness center. Near Jordan Creek Town Center and major corporate offices in West Des Moines.',
  '1236 Jordan Creek Pkwy',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 223-5566',
  'https://www.marriott.com/hotels/travel/dsmsh-springhill-suites-des-moines-west/',
  3.0, '$$', 119, 'Hotel', 'SpringHill Suites', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Suite Available', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Fairfield Inn & Suites Des Moines West',
  'fairfield-inn-des-moines-west',
  'Affordable Marriott property in West Des Moines.',
  'Fairfield Inn & Suites Des Moines West provides comfortable, affordable accommodations with free breakfast, pool, and fitness center. Convenient West Des Moines location near Jordan Creek Town Center.',
  '7225 Vista Dr',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 226-0300',
  'https://www.marriott.com/hotels/travel/dsmfw-fairfield-inn-and-suites-des-moines-west/',
  2.5, '$$', 99, 'Hotel', 'Fairfield Inn & Suites', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Element West Des Moines',
  'element-west-des-moines',
  'Eco-conscious extended stay Marriott in West Des Moines.',
  'Element West Des Moines is a nature-inspired, eco-conscious extended stay hotel by Marriott. Features spacious rooms with full kitchens, a pool, and fitness center. Pet-friendly and designed for longer stays.',
  '575 S Prairie View Dr',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 223-2424',
  'https://www.marriott.com/hotels/travel/dsmel-element-west-des-moines/',
  3.0, '$$', 119, 'Extended Stay', 'Element', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Free Parking', 'Suite Available', 'Pet Friendly', 'EV Charging'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Holiday Inn Express & Suites West Des Moines Jordan Creek',
  'holiday-inn-express-west-des-moines',
  'IHG express hotel near Jordan Creek with free breakfast.',
  'Holiday Inn Express & Suites West Des Moines/Jordan Creek offers comfortable rooms with complimentary Express Start breakfast, indoor pool, and free parking. Walking distance to Jordan Creek Town Center.',
  '240 S Jordan Creek Pkwy',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 225-1100',
  'https://www.ihg.com/holidayinnexpress/hotels/us/en/west-des-moines/dsmjc/hoteldetail',
  2.5, '$$', 109, 'Hotel', 'Holiday Inn Express', 'IHG',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Pet Friendly', 'Business Center'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Staybridge Suites West Des Moines',
  'staybridge-suites-west-des-moines',
  'All-suite extended stay hotel with full kitchens near Jordan Creek.',
  'Staybridge Suites West Des Moines offers spacious suites with full kitchens, perfect for extended stays or families. Located near Jordan Creek Town Center with easy access to I-80/I-35. Includes complimentary breakfast and evening social receptions.',
  '6905 Lake Dr',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 223-0000',
  'https://www.ihg.com/staybridge/hotels/us/en/west-des-moines/dsmwb/hoteldetail',
  3.0, '$$', 119, 'Extended Stay', 'Staybridge Suites', 'IHG',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Pet Friendly', 'Suite Available', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Drury Inn & Suites West Des Moines',
  'drury-inn-west-des-moines',
  'Family-owned Drury hotel with free hot breakfast and evening kickback.',
  'Drury Inn & Suites West Des Moines offers exceptional value with complimentary hot breakfast and a free evening "5:30 Kickback" with food and drinks. Indoor/outdoor pool, fitness center, and business center included.',
  '5505 Mills Civic Pkwy',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 225-2626',
  'https://www.druryhotels.com/locations/west-des-moines-ia/drury-inn-and-suites-west-des-moines',
  3.0, '$$', 119, 'Hotel', 'Drury Inn', 'Drury',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Sleep Inn & Suites West Des Moines',
  'sleep-inn-west-des-moines',
  'Budget-friendly Choice Hotels property in West Des Moines.',
  'Sleep Inn & Suites West Des Moines offers clean, comfortable rooms at a budget-friendly price. Complimentary breakfast, free WiFi, and a smoke-free environment near Jordan Creek Town Center.',
  '885 S 51st St',
  'West Des Moines', 'IA', '50265',
  'West Des Moines',
  '(515) 221-4200',
  'https://www.choicehotels.com/iowa/west-des-moines/sleep-inn-hotels/ia501',
  2.0, '$', 79, 'Hotel', 'Sleep Inn', 'Choice',
  ARRAY['Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Comfort Inn & Suites West Des Moines',
  'comfort-inn-west-des-moines',
  'Comfortable Choice Hotels property near Jordan Creek.',
  'Comfort Inn & Suites West Des Moines provides affordable comfort with an indoor pool, complimentary breakfast, fitness center, and free parking. Near Jordan Creek Town Center shopping.',
  '1625 Jordan Creek Pkwy',
  'West Des Moines', 'IA', '50266',
  'West Des Moines',
  '(515) 223-9700',
  'https://www.choicehotels.com/iowa/west-des-moines/comfort-inn-hotels/ia367',
  2.5, '$', 89, 'Hotel', 'Comfort Inn', 'Choice',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking'],
  false, true, '3:00 PM', '11:00 AM'
),

-- =====================================================
-- CLIVE (I-35/I-80 Interchange)
-- =====================================================
(
  'Best Western Plus Des Moines West Inn & Suites',
  'best-western-plus-clive',
  'Best Western Plus hotel at the I-35/I-80 interchange in Clive.',
  'Best Western Plus Des Moines West Inn & Suites offers comfortable accommodations at the I-35/I-80 interchange. Features complimentary breakfast, indoor pool, fitness center, and free parking. Convenient access to all Des Moines metro attractions.',
  '1450 NW 118th St',
  'Clive', 'IA', '50325',
  'Clive',
  '(515) 221-2345',
  'https://www.bestwestern.com/en_US/book/hotels-in-clive/best-western-plus-des-moines-west-inn-and-suites/propertyCode.16165.html',
  2.5, '$$', 99, 'Hotel', 'Best Western Plus', 'Best Western',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'La Quinta Inn & Suites by Wyndham Clive',
  'la-quinta-clive',
  'Pet-friendly Wyndham property at the I-35/I-80 interchange.',
  'La Quinta Inn & Suites by Wyndham Clive offers comfortable, pet-friendly accommodations at the I-35/I-80 interchange. Features complimentary breakfast, pool, fitness center, and free parking.',
  '1390 NW 118th St',
  'Clive', 'IA', '50325',
  'Clive',
  '(515) 221-9200',
  'https://www.wyndhamhotels.com/laquinta/clive-iowa/la-quinta-des-moines-west-clive/overview',
  2.5, '$$', 89, 'Hotel', 'La Quinta', 'Wyndham',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Pet Friendly'],
  false, true, '3:00 PM', '11:00 AM'
),

-- =====================================================
-- URBANDALE / JOHNSTON
-- =====================================================
(
  'Hotel Renovo, Tapestry Collection by Hilton',
  'hotel-renovo-urbandale',
  'Boutique farmhouse-style hotel in Urbandale with pool and bistro.',
  'Hotel Renovo is a boutique property in Hilton''s Tapestry Collection, featuring a modern farmhouse aesthetic in Urbandale. Enjoy the indoor pool, hot tub, bistro & bar, and unique design-forward accommodations near Merle Hay Mall.',
  '11167 Hickman Rd',
  'Urbandale', 'IA', '50322',
  'Urbandale',
  '(515) 270-8890',
  'https://www.hilton.com/en/hotels/dsmurup-hotel-renovo-des-moines-urbandale/',
  4.5, '$$$', 149, 'Boutique Hotel', 'Tapestry Collection', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Free Parking'],
  true, true, '3:00 PM', '12:00 PM'
),
(
  'Holiday Inn & Suites Des Moines Northwest',
  'holiday-inn-urbandale',
  'Full-service IHG hotel on Merle Hay Road in Urbandale.',
  'Holiday Inn & Suites Des Moines Northwest in Urbandale offers a bar, pool, fitness center, and free parking on Merle Hay Road. Convenient access to downtown Des Moines and suburban attractions.',
  '4800 Merle Hay Rd',
  'Urbandale', 'IA', '50322',
  'Urbandale',
  '(515) 278-4755',
  'https://www.ihg.com/holidayinn/hotels/us/en/urbandale/dsmnw/hoteldetail',
  3.0, '$$', 109, 'Hotel', 'Holiday Inn', 'IHG',
  ARRAY['Pool', 'Fitness Center', 'Bar/Lounge', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Holiday Inn Express & Suites Urbandale',
  'holiday-inn-express-urbandale',
  'IHG express hotel with free breakfast in Urbandale.',
  'Holiday Inn Express & Suites Urbandale offers comfortable rooms with complimentary Express Start breakfast, indoor pool, and fitness center. Convenient Urbandale location with easy access to I-35/I-80.',
  '8789 Plum Dr',
  'Urbandale', 'IA', '50322',
  'Urbandale',
  '(515) 331-2555',
  'https://www.ihg.com/holidayinnexpress/hotels/us/en/urbandale/dsmub/hoteldetail',
  2.5, '$$', 99, 'Hotel', 'Holiday Inn Express', 'IHG',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Homewood Suites by Hilton Urbandale',
  'homewood-suites-urbandale',
  'All-suite extended stay hotel in Urbandale with free breakfast.',
  'Homewood Suites by Hilton Urbandale offers spacious all-suite accommodations with full kitchens, complimentary breakfast, and an evening social reception. Indoor pool and fitness center included.',
  '8901 Plum Dr',
  'Urbandale', 'IA', '50322',
  'Urbandale',
  '(515) 270-2222',
  'https://www.hilton.com/en/hotels/dsmubhw-homewood-suites-urbandale-des-moines/',
  3.0, '$$', 119, 'Extended Stay', 'Homewood Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Suite Available', 'Pet Friendly'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'TownePlace Suites Des Moines Urbandale',
  'towneplace-suites-johnston',
  'Extended stay suites near Johnston and Urbandale.',
  'TownePlace Suites Des Moines Urbandale offers affordable extended-stay suites with fully equipped kitchens, complimentary breakfast, and indoor pool. Convenient location between Johnston and Urbandale.',
  '8800 Northpark Dr',
  'Johnston', 'IA', '50131',
  'Johnston',
  '(515) 727-4066',
  'https://www.marriott.com/hotels/travel/dsmtu-towneplace-suites-des-moines-urbandale/',
  2.5, '$$', 99, 'Extended Stay', 'TownePlace Suites', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Suite Available', 'Pet Friendly'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Stoney Creek Hotel Des Moines Johnston',
  'stoney-creek-johnston',
  'Unique lodge-style hotel and conference center in Johnston.',
  'Stoney Creek Hotel & Conference Center in Johnston features a distinctive Northwoods lodge atmosphere with indoor pool, hot tub, and conference center. A unique independent hotel option in the Des Moines metro.',
  '5291 Stoney Creek Ct',
  'Johnston', 'IA', '50131',
  'Johnston',
  '(515) 334-9000',
  'https://www.stoneycreekhotels.com/hotel/johnston-des-moines/',
  3.0, '$$', 109, 'Hotel', 'Stoney Creek', 'Independent',
  ARRAY['Pool', 'Fitness Center', 'Free Parking', 'Business Center', 'Suite Available'],
  false, true, '3:00 PM', '11:00 AM'
),

-- =====================================================
-- ANKENY
-- =====================================================
(
  'Best Western Premier Ankeny Hotel',
  'best-western-premier-ankeny',
  'Upscale Best Western in Ankeny with full breakfast buffet.',
  'Best Western Premier Ankeny Hotel offers upscale accommodations with a full breakfast buffet, indoor heated pool, fitness center, and modern walk-in showers. Conveniently located off I-35 in one of Iowa''s fastest-growing communities.',
  '2502 SE Tones Dr',
  'Ankeny', 'IA', '50021',
  'Ankeny',
  '(515) 964-8882',
  'https://www.bestwestern.com/en_US/book/hotels-in-ankeny/best-western-premier-ankeny-hotel/propertyCode.16110.html',
  3.0, '$$', 109, 'Hotel', 'Best Western Premier', 'Best Western',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Hampton Inn & Suites Ankeny',
  'hampton-inn-ankeny',
  'Family-friendly Hampton in Ankeny with free breakfast.',
  'Hampton Inn & Suites Ankeny offers comfortable accommodations with complimentary hot breakfast, indoor pool, and fitness center. Easy access to I-35 and DMACC campus.',
  '6210 SE Convenience Blvd',
  'Ankeny', 'IA', '50021',
  'Ankeny',
  '(515) 964-2100',
  'https://www.hilton.com/en/hotels/dsmakhx-hampton-suites-ankeny/',
  3.0, '$$', 109, 'Hotel', 'Hampton Inn & Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),

-- =====================================================
-- ALTOONA (Adventureland / Prairie Meadows / Bass Pro)
-- =====================================================
(
  'Prairie Meadows Casino, Racetrack & Hotel',
  'prairie-meadows-casino-hotel',
  'Full-service casino resort with entertainment, dining, and gaming in Altoona.',
  'Prairie Meadows is Iowa''s premier entertainment destination featuring a hotel, casino, racetrack, and multiple dining options. Located in Altoona near Adventureland amusement park, it offers a complete resort experience with gaming, live entertainment, and comfortable accommodations.',
  '1 Prairie Meadows Dr',
  'Altoona', 'IA', '50009',
  'Altoona',
  '(515) 967-1000',
  'https://www.prairiemeadows.com/',
  3.5, '$$', 109, 'Resort', 'Prairie Meadows', 'Independent',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Spa', 'Free Parking', 'Suite Available'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Hyatt Place Altoona Des Moines',
  'hyatt-place-altoona',
  'Modern Hyatt near Adventureland and Bass Pro with free breakfast.',
  'Hyatt Place Altoona/Des Moines offers a modern stay near Adventureland, Prairie Meadows Casino, and Bass Pro Shops. Complimentary breakfast, indoor pool, and fitness center included.',
  '480 Bass Pro Dr NW',
  'Altoona', 'IA', '50009',
  'Altoona',
  '(515) 967-2400',
  'https://www.hyatt.com/hyatt-place/en-US/dsmza-hyatt-place-altoona-des-moines',
  3.0, '$$', 119, 'Hotel', 'Hyatt Place', 'Hyatt',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Hampton Inn & Suites Altoona Des Moines',
  'hampton-inn-altoona',
  'Family-friendly Hampton near Adventureland and Prairie Meadows.',
  'Hampton Inn & Suites Altoona provides comfortable accommodations near Adventureland amusement park and Prairie Meadows Casino. Features complimentary hot breakfast, indoor pool, and fitness center.',
  '215 Adventureland Dr NW',
  'Altoona', 'IA', '50009',
  'Altoona',
  '(515) 967-5000',
  'https://www.hilton.com/en/hotels/dsmalhx-hampton-suites-altoona-des-moines/',
  3.0, '$$', 109, 'Hotel', 'Hampton Inn & Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Home2 Suites by Hilton Altoona Des Moines',
  'home2-suites-altoona',
  'Extended stay suites near Adventureland with kitchen amenities.',
  'Home2 Suites by Hilton Altoona Des Moines offers modern extended-stay suites with kitchen amenities, indoor pool, and laundry facilities. Near Adventureland and Prairie Meadows Casino.',
  '255 Adventureland Dr NW',
  'Altoona', 'IA', '50009',
  'Altoona',
  '(515) 967-0200',
  'https://www.hilton.com/en/hotels/dsmalht-home2-suites-altoona-des-moines/',
  3.0, '$$', 99, 'Extended Stay', 'Home2 Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Parking', 'Suite Available', 'Pet Friendly'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Holiday Inn Express & Suites Altoona',
  'holiday-inn-express-altoona',
  'IHG express hotel near Adventureland with free breakfast.',
  'Holiday Inn Express & Suites Altoona offers comfortable rooms with complimentary Express Start breakfast, indoor pool, and fitness center. Near Adventureland amusement park and Prairie Meadows Casino.',
  '165 Adventureland Dr NW',
  'Altoona', 'IA', '50009',
  'Altoona',
  '(515) 967-0100',
  'https://www.ihg.com/holidayinnexpress/hotels/us/en/altoona/dsmat/hoteldetail',
  2.5, '$$', 99, 'Hotel', 'Holiday Inn Express', 'IHG',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Fairfield Inn & Suites Altoona Des Moines',
  'fairfield-inn-altoona',
  'Affordable Marriott hotel near Adventureland in Altoona.',
  'Fairfield Inn & Suites Altoona provides comfortable, affordable accommodations with free breakfast, pool, and fitness center near Adventureland and Bass Pro Shops.',
  '460 Bass Pro Dr NW',
  'Altoona', 'IA', '50009',
  'Altoona',
  '(515) 967-3888',
  'https://www.marriott.com/hotels/travel/dsmal-fairfield-inn-and-suites-des-moines-altoona/',
  2.5, '$$', 99, 'Hotel', 'Fairfield Inn & Suites', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Comfort Suites Altoona',
  'comfort-suites-altoona',
  'Family-friendly hotel near Adventureland and Prairie Meadows.',
  'Comfort Suites Altoona is a family-friendly hotel conveniently located near Adventureland amusement park and Prairie Meadows Casino. Features spacious suites, indoor pool, complimentary breakfast, and easy access to I-80.',
  '3825 Adventureland Dr',
  'Altoona', 'IA', '50009',
  'Altoona',
  '(515) 967-7070',
  'https://www.choicehotels.com/iowa/altoona/comfort-suites-hotels/ia388',
  2.5, '$', 89, 'Hotel', 'Comfort Suites', 'Choice',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Pet Friendly', 'Suite Available'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Best Western Plus Altoona Inn',
  'best-western-plus-altoona',
  'Comfortable Best Western near Adventureland and Prairie Meadows.',
  'Best Western Plus Altoona Inn offers comfortable accommodations with complimentary breakfast, indoor pool, fitness center, and free parking. Near Adventureland and Prairie Meadows Casino.',
  '300 34th Ave NW',
  'Altoona', 'IA', '50009',
  'Altoona',
  '(515) 967-2014',
  'https://www.bestwestern.com/en_US/book/hotels-in-altoona/best-western-plus-altoona-inn/propertyCode.16165.html',
  2.5, '$$', 89, 'Hotel', 'Best Western Plus', 'Best Western',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'La Quinta by Wyndham Altoona Des Moines',
  'la-quinta-altoona',
  'Pet-friendly Wyndham property near Adventureland.',
  'La Quinta by Wyndham Altoona offers comfortable, pet-friendly accommodations near Adventureland and Prairie Meadows. Features complimentary breakfast, indoor pool, and fitness center.',
  '1785 11th St NW',
  'Altoona', 'IA', '50009',
  'Altoona',
  '(515) 957-1090',
  'https://www.wyndhamhotels.com/laquinta/altoona-iowa/la-quinta-altoona-des-moines/overview',
  3.0, '$$', 89, 'Hotel', 'La Quinta', 'Wyndham',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Pet Friendly'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Quality Inn & Suites Altoona',
  'quality-inn-altoona',
  'Budget-friendly hotel near Adventureland amusement park.',
  'Quality Inn & Suites Altoona offers budget-friendly accommodations near Adventureland amusement park with indoor pool, complimentary breakfast, and free parking.',
  '2701 Adventureland Dr',
  'Altoona', 'IA', '50009',
  'Altoona',
  '(515) 967-2000',
  'https://www.choicehotels.com/iowa/altoona/quality-inn-hotels/ia260',
  2.0, '$', 69, 'Hotel', 'Quality Inn', 'Choice',
  ARRAY['Pool', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '11:00 AM'
),

-- =====================================================
-- WAUKEE / GRIMES
-- =====================================================
(
  'Hampton Inn & Suites Waukee',
  'hampton-inn-suites-waukee',
  'Modern Hampton property near the Horizon Events Center in Waukee.',
  'The Hampton Inn & Suites Waukee provides comfortable accommodations near the Horizon Events Center, making it ideal for concert and event-goers. Features include complimentary hot breakfast, indoor pool, fitness center, and free parking.',
  '785 SE Destination Dr',
  'Waukee', 'IA', '50263',
  'Waukee',
  '(515) 987-2333',
  'https://www.hilton.com/en/hotels/dsmwkhx-hampton-suites-waukee/',
  3.0, '$$', 119, 'Hotel', 'Hampton Inn & Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Aloft Waukee',
  'aloft-waukee',
  'Modern, trendy Marriott lifestyle hotel in KeeTown Loop, Waukee.',
  'Aloft Waukee is a modern, trendy hotel by Marriott in the exciting KeeTown Loop development in Waukee. Features a vibrant bar, pool, fitness center, and a youthful, design-forward atmosphere. Near Horizon Events Center.',
  '2848 Grand Prairie Pkwy',
  'Waukee', 'IA', '50263',
  'Waukee',
  '(515) 987-5100',
  'https://www.marriott.com/hotels/travel/dsmwa-aloft-waukee/',
  3.0, '$$', 129, 'Boutique Hotel', 'Aloft', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Bar/Lounge', 'Free Parking', 'Pet Friendly'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Tru by Hilton Grimes Des Moines',
  'tru-by-hilton-grimes',
  'Modern budget-friendly Hilton in Grimes with free breakfast.',
  'Tru by Hilton Grimes Des Moines is a modern, vibrant budget-friendly hotel offering complimentary breakfast, fitness center, and a social lounge. Perfect for value-conscious travelers exploring the Des Moines metro.',
  '701 NE Gateway Dr',
  'Grimes', 'IA', '50111',
  'Grimes',
  '(515) 986-3200',
  'https://www.hilton.com/en/hotels/dsmgsru-tru-grimes-des-moines/',
  2.5, '$$', 89, 'Hotel', 'Tru by Hilton', 'Hilton',
  ARRAY['Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),

-- =====================================================
-- AMES (35 miles north - Iowa State University)
-- =====================================================
(
  'Courtyard by Marriott Ames',
  'courtyard-ames',
  'Marriott Courtyard in Ames near Iowa State University.',
  'The Courtyard by Marriott Ames offers comfortable accommodations near Iowa State University. Features The Bistro restaurant, indoor pool, fitness center, and meeting space. Great for game days and campus visits.',
  '311 S 17th St',
  'Ames', 'IA', '50010',
  'Ames',
  '(515) 232-8100',
  'https://www.marriott.com/hotels/travel/dsmam-courtyard-ames/',
  3.0, '$$', 119, 'Hotel', 'Courtyard', 'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Hampton Inn & Suites Ames',
  'hampton-inn-ames',
  'Family-friendly Hampton near Iowa State University.',
  'Hampton Inn & Suites Ames offers complimentary hot breakfast, indoor pool, and fitness center near Iowa State University. Popular for game day weekends, campus visits, and business travel.',
  '2100 SE 16th St',
  'Ames', 'IA', '50010',
  'Ames',
  '(515) 239-9999',
  'https://www.hilton.com/en/hotels/amsiahx-hampton-suites-ames/',
  3.0, '$$', 109, 'Hotel', 'Hampton Inn & Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Holiday Inn Express Ames',
  'holiday-inn-express-ames',
  'IHG express hotel in Ames near Iowa State University.',
  'Holiday Inn Express Ames provides comfortable rooms with complimentary Express Start breakfast, pool, and fitness center. Convenient location near Iowa State University campus.',
  '2600 E 13th St',
  'Ames', 'IA', '50010',
  'Ames',
  '(515) 232-2300',
  'https://www.ihg.com/holidayinnexpress/hotels/us/en/ames/amsia/hoteldetail',
  2.5, '$$', 99, 'Hotel', 'Holiday Inn Express', 'IHG',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false, true, '3:00 PM', '11:00 AM'
),
(
  'Home2 Suites by Hilton Ames',
  'home2-suites-ames',
  'Extended stay suites in Ames near Iowa State.',
  'Home2 Suites by Hilton Ames offers modern extended-stay suites with kitchen amenities near Iowa State University. Features an indoor pool, laundry, and complimentary breakfast.',
  '1610 S Kellogg Ave',
  'Ames', 'IA', '50010',
  'Ames',
  '(515) 598-9700',
  'https://www.hilton.com/en/hotels/amsiaht-home2-suites-ames/',
  3.0, '$$', 99, 'Extended Stay', 'Home2 Suites', 'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Suite Available', 'Pet Friendly'],
  false, true, '3:00 PM', '12:00 PM'
),
(
  'Comfort Inn & Suites Ames',
  'comfort-inn-ames',
  'Affordable Choice Hotels property in Ames near Iowa State.',
  'Comfort Inn & Suites Ames offers comfortable accommodations with complimentary breakfast, indoor pool, and free parking near Iowa State University. Affordable option for campus visits and game days.',
  '1602 S Dayton Ave',
  'Ames', 'IA', '50010',
  'Ames',
  '(515) 232-0689',
  'https://www.choicehotels.com/iowa/ames/comfort-inn-hotels/ia172',
  2.5, '$', 79, 'Hotel', 'Comfort Inn', 'Choice',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking'],
  false, true, '3:00 PM', '11:00 AM'
);
