-- Seed starter hotel data for Des Moines area
-- Priority hotels in high-traffic areas

INSERT INTO public.hotels (name, slug, short_description, description, address, city, state, zip, area, phone, website, star_rating, price_range, avg_nightly_rate, hotel_type, chain_name, amenities, is_featured, is_active, check_in_time, check_out_time) VALUES

-- Downtown Des Moines
(
  'Hilton Des Moines Downtown',
  'hilton-des-moines-downtown',
  'Full-service Hilton in the heart of downtown, connected to the skywalk system.',
  'Located in the center of downtown Des Moines, the Hilton Des Moines Downtown offers easy access to the Iowa Events Center, Wells Fargo Arena, and the Des Moines Civic Center via the skywalk system. The hotel features modern rooms, an on-site restaurant, indoor pool, and fitness center.',
  '435 Park St',
  'Des Moines',
  'IA',
  '50309',
  'Downtown',
  '(515) 241-1456',
  'https://www.hilton.com/en/hotels/dsmhihf-hilton-des-moines-downtown/',
  4.0,
  '$$$',
  169,
  'Hotel',
  'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Business Center', 'Free Parking'],
  true,
  true,
  '3:00 PM',
  '12:00 PM'
),
(
  'Des Moines Marriott Downtown',
  'des-moines-marriott-downtown',
  'Upscale Marriott property steps from the Capitol and Court Avenue.',
  'The Des Moines Marriott Downtown is a premier hotel offering upscale accommodations in the heart of the city. Walking distance to the Iowa State Capitol, Court Avenue Entertainment District, and connected to the skywalk. Features include a rooftop bar, indoor pool, and full fitness center.',
  '700 Grand Ave',
  'Des Moines',
  'IA',
  '50309',
  'Downtown',
  '(515) 245-5500',
  'https://www.marriott.com/hotels/travel/dsmia-des-moines-marriott-downtown/',
  4.0,
  '$$$',
  179,
  'Hotel',
  'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Business Center', 'Suite Available'],
  true,
  true,
  '4:00 PM',
  '11:00 AM'
),
(
  'Hotel Fort Des Moines',
  'hotel-fort-des-moines',
  'Historic boutique hotel with modern luxury in downtown Des Moines.',
  'Originally built in 1919, Hotel Fort Des Moines is a beautifully restored historic landmark that blends classic architecture with modern amenities. Located in the heart of downtown, it offers a unique boutique experience with spacious rooms, an on-site restaurant, and elegant event spaces.',
  '1000 Walnut St',
  'Des Moines',
  'IA',
  '50309',
  'Downtown',
  '(515) 243-1161',
  'https://www.hotelfortdesmoines.com/',
  4.0,
  '$$$',
  159,
  'Boutique Hotel',
  NULL,
  ARRAY['Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Business Center', 'Suite Available'],
  true,
  true,
  '3:00 PM',
  '11:00 AM'
),
(
  'Surety Hotel',
  'surety-hotel',
  'Boutique hotel in a beautifully restored 1913 building in downtown Des Moines.',
  'Surety Hotel is a boutique property housed in a stunning 1913 building in downtown Des Moines. It features thoughtfully designed rooms, the acclaimed Mulberry Street Tavern restaurant, and a rooftop patio. Perfect for travelers seeking a unique, design-forward experience.',
  '206 6th Ave',
  'Des Moines',
  'IA',
  '50309',
  'Downtown',
  '(515) 985-1171',
  'https://www.suretyhotel.com/',
  4.5,
  '$$$$',
  219,
  'Boutique Hotel',
  NULL,
  ARRAY['Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Suite Available'],
  true,
  true,
  '3:00 PM',
  '11:00 AM'
),
(
  'AC Hotel Des Moines East Village',
  'ac-hotel-des-moines-east-village',
  'Modern Marriott lifestyle hotel in the vibrant East Village neighborhood.',
  'The AC Hotel by Marriott in the East Village offers a sleek, European-inspired design in one of Des Moines'' most walkable neighborhoods. Steps from local boutiques, restaurants, and the Des Moines Farmers'' Market. Features a rooftop bar with skyline views.',
  '401 E Grand Ave',
  'Des Moines',
  'IA',
  '50309',
  'Downtown',
  '(515) 518-5560',
  'https://www.marriott.com/hotels/travel/dsmac-ac-hotel-des-moines-east-village/',
  4.0,
  '$$$',
  189,
  'Boutique Hotel',
  'Marriott',
  ARRAY['Fitness Center', 'Bar/Lounge', 'Business Center'],
  true,
  true,
  '3:00 PM',
  '12:00 PM'
),

-- West Des Moines / Waukee
(
  'Hilton Garden Inn West Des Moines',
  'hilton-garden-inn-west-des-moines',
  'Comfortable Hilton property near Jordan Creek and I-80/I-35.',
  'The Hilton Garden Inn West Des Moines is ideally located near Jordan Creek Town Center, offering easy access to shopping, dining, and entertainment. Features include an indoor pool, fitness center, on-site restaurant, and complimentary parking.',
  '205 S 64th St',
  'West Des Moines',
  'IA',
  '50266',
  'West Des Moines',
  '(515) 225-2000',
  'https://www.hilton.com/en/hotels/dsmwdgi-hilton-garden-inn-west-des-moines/',
  3.5,
  '$$',
  129,
  'Hotel',
  'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Restaurant On-Site', 'Business Center'],
  false,
  true,
  '3:00 PM',
  '12:00 PM'
),
(
  'Staybridge Suites West Des Moines',
  'staybridge-suites-west-des-moines',
  'All-suite extended stay hotel with full kitchens near Jordan Creek.',
  'Staybridge Suites West Des Moines offers spacious suites with full kitchens, perfect for extended stays or families. Located near Jordan Creek Town Center with easy access to I-80/I-35. Includes complimentary breakfast, evening social receptions, and an outdoor pool.',
  '6905 Lake Dr',
  'West Des Moines',
  'IA',
  '50266',
  'West Des Moines',
  '(515) 223-0000',
  'https://www.ihg.com/staybridge/hotels/us/en/west-des-moines/',
  3.0,
  '$$',
  119,
  'Extended Stay',
  'IHG',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Pet Friendly', 'Suite Available', 'Business Center'],
  false,
  true,
  '3:00 PM',
  '12:00 PM'
),
(
  'Hampton Inn & Suites Waukee',
  'hampton-inn-suites-waukee',
  'Modern Hampton property near the Horizon Events Center in Waukee.',
  'The Hampton Inn & Suites Waukee provides comfortable accommodations near the Horizon Events Center, making it ideal for concert and event-goers. Features include complimentary hot breakfast, indoor pool, fitness center, and free parking.',
  '785 SE Destination Dr',
  'Waukee',
  'IA',
  '50263',
  'Waukee',
  '(515) 987-2333',
  'https://www.hilton.com/en/hotels/dsmwkhx-hampton-suites-waukee/',
  3.0,
  '$$',
  139,
  'Hotel',
  'Hilton',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Business Center'],
  false,
  true,
  '3:00 PM',
  '12:00 PM'
),
(
  'Courtyard by Marriott West Des Moines',
  'courtyard-by-marriott-west-des-moines',
  'Reliable Marriott hotel near Valley West Mall and I-235.',
  'The Courtyard by Marriott West Des Moines offers a convenient location with easy access to downtown Des Moines via I-235. Features modern rooms, a bistro restaurant, indoor pool, and fitness center.',
  '1500 114th St',
  'West Des Moines',
  'IA',
  '50266',
  'West Des Moines',
  '(515) 223-9600',
  'https://www.marriott.com/hotels/travel/dsmcy-courtyard-des-moines-west-des-moines/',
  3.0,
  '$$',
  129,
  'Hotel',
  'Marriott',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Free Parking', 'Business Center'],
  false,
  true,
  '3:00 PM',
  '12:00 PM'
),

-- I-80/I-35 Corridor
(
  'Prairie Meadows Casino, Racetrack & Hotel',
  'prairie-meadows-casino-hotel',
  'Full-service casino resort with entertainment, dining, and gaming in Altoona.',
  'Prairie Meadows is Iowa''s premier entertainment destination featuring a hotel, casino, racetrack, and multiple dining options. Located in Altoona near Adventureland amusement park, it offers a complete resort experience with gaming, live entertainment, and comfortable accommodations.',
  '1 Prairie Meadows Dr',
  'Altoona',
  'IA',
  '50009',
  'Altoona',
  '(515) 967-1000',
  'https://www.prairiemeadows.com/',
  3.5,
  '$$',
  109,
  'Resort',
  NULL,
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Bar/Lounge', 'Spa', 'Free Parking', 'Suite Available'],
  false,
  true,
  '3:00 PM',
  '11:00 AM'
),
(
  'Comfort Suites Altoona',
  'comfort-suites-altoona',
  'Family-friendly hotel near Adventureland and Prairie Meadows.',
  'Comfort Suites Altoona is a family-friendly hotel conveniently located near Adventureland amusement park and Prairie Meadows Casino. Features spacious suites, indoor pool, complimentary breakfast, and easy access to I-80.',
  '3825 Adventureland Dr',
  'Altoona',
  'IA',
  '50009',
  'Altoona',
  '(515) 967-7070',
  'https://www.choicehotels.com/iowa/altoona/comfort-suites-hotels/',
  2.5,
  '$',
  89,
  'Hotel',
  'Choice Hotels',
  ARRAY['Pool', 'Fitness Center', 'Free Breakfast', 'Free Parking', 'Pet Friendly', 'Suite Available'],
  false,
  true,
  '3:00 PM',
  '11:00 AM'
),
(
  'Holiday Inn Des Moines - Airport',
  'holiday-inn-des-moines-airport',
  'Convenient airport hotel with free shuttle and easy highway access.',
  'The Holiday Inn Des Moines Airport offers a convenient stay for travelers flying into Des Moines International Airport. Features include a complimentary airport shuttle, indoor pool, on-site restaurant, and easy access to I-80 and I-35.',
  '6111 Fleur Dr',
  'Des Moines',
  'IA',
  '50321',
  'Downtown',
  '(515) 287-2400',
  'https://www.ihg.com/holidayinn/hotels/us/en/des-moines/',
  3.0,
  '$$',
  109,
  'Hotel',
  'IHG',
  ARRAY['Pool', 'Fitness Center', 'Restaurant On-Site', 'Free Parking', 'Airport Shuttle', 'Business Center'],
  false,
  true,
  '3:00 PM',
  '11:00 AM'
);
