// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// SECURITY FIX: Load credentials from environment variables
// Fallback values for development only - NEVER use in production
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://wtkhfqpmcegzcbngroui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0a2hmcXBtY2VnemNibmdyb3VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Mzc5NzcsImV4cCI6MjA2OTExMzk3N30.a-qKhaxy7l72IyT0eLq7kYuxm-wypuMxgycDy95r1aE";

// Validate environment variables in production
if (import.meta.env.PROD && (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY)) {
  throw new Error('Missing required environment variables: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set in production');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      // Detect session timeout and force re-authentication
      detectSessionInUrl: true,
      flowType: 'pkce', // Use PKCE flow for enhanced security
    },
    global: {
      headers: {
        'X-Client-Info': 'desmoines-ai-pulse',
      },
    },
  }
);

// Session timeout is now handled by Supabase's built-in token refresh mechanism
// This prevents mid-navigation logouts and race conditions
// Supabase automatically refreshes tokens before expiry and handles session management
