// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// SECURITY: Environment variables are required - no hardcoded fallbacks
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables are always present
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing required Supabase environment variables. ' +
    'Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your environment.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      // Detect session timeout and force re-authentication
      detectSessionInUrl: true,
      flowType: 'pkce', // Use PKCE flow for enhanced security
    },
    global: {
      headers: {
        'X-Client-Info': 'desmoines-ai-pulse',
      },
    },
  }
);

// Session timeout is now handled by Supabase's built-in token refresh mechanism
// This prevents mid-navigation logouts and race conditions
// Supabase automatically refreshes tokens before expiry and handles session management
