// GENERATED by scripts/generate-icon-sprite.mjs from lucide-react 0.462.0.
// Do not edit. Run `npm run icons:sprite` after upgrading lucide-react.
//
// Shape and attribute defaults are copied from lucide's own Icon.js /
// defaultAttributes.js, so <SpriteIcon name="clock" /> renders the same pixels
// as <Clock /> - see src/components/ui/SpriteIcon.tsx.

export const SPRITE_ICON_NAMES = [
  'arrow-right',
  'building-2',
  'calendar',
  'chef-hat',
  'clock',
  'external-link',
  'map-pin',
  'share-2',
  'sparkles',
  'ticket',
  'trending-up',
  'users',
] as const;

export type SpriteIconName = (typeof SPRITE_ICON_NAMES)[number];

/**
 * Mounted once, near the root. Renders nothing visible; every <SpriteIcon />
 * on the page references these symbols by id.
 */
export function LucideSprite() {
  return (
    <svg
      aria-hidden="true"
      focusable="false"
      style={{ position: 'absolute', width: 0, height: 0, overflow: 'hidden' }}
      xmlns="http://www.w3.org/2000/svg"
    >
    <symbol id="lu-arrow-right" viewBox="0 0 24 24">
      <path d="M5 12h14" key="1ays0h" />
      <path d="m12 5 7 7-7 7" key="xquz4c" />
    </symbol>
    <symbol id="lu-building-2" viewBox="0 0 24 24">
      <path d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z" key="1b4qmf" />
      <path d="M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2" key="i71pzd" />
      <path d="M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2" key="10jefs" />
      <path d="M10 6h4" key="1itunk" />
      <path d="M10 10h4" key="tcdvrf" />
      <path d="M10 14h4" key="kelpxr" />
      <path d="M10 18h4" key="1ulq68" />
    </symbol>
    <symbol id="lu-calendar" viewBox="0 0 24 24">
      <path d="M8 2v4" key="1cmpym" />
      <path d="M16 2v4" key="4m81vk" />
      <rect width="18" height="18" x="3" y="4" rx="2" key="1hopcy" />
      <path d="M3 10h18" key="8toen8" />
    </symbol>
    <symbol id="lu-chef-hat" viewBox="0 0 24 24">
      <path d="M17 21a1 1 0 0 0 1-1v-5.35c0-.457.316-.844.727-1.041a4 4 0 0 0-2.134-7.589 5 5 0 0 0-9.186 0 4 4 0 0 0-2.134 7.588c.411.198.727.585.727 1.041V20a1 1 0 0 0 1 1Z" key="1qvrer" />
      <path d="M6 17h12" key="1jwigz" />
    </symbol>
    <symbol id="lu-clock" viewBox="0 0 24 24">
      <circle cx="12" cy="12" r="10" key="1mglay" />
      <polyline points="12 6 12 12 16 14" key="68esgv" />
    </symbol>
    <symbol id="lu-external-link" viewBox="0 0 24 24">
      <path d="M15 3h6v6" key="1q9fwt" />
      <path d="M10 14 21 3" key="gplh6r" />
      <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" key="a6xqqp" />
    </symbol>
    <symbol id="lu-map-pin" viewBox="0 0 24 24">
      <path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0" key="1r0f0z" />
      <circle cx="12" cy="10" r="3" key="ilqhr7" />
    </symbol>
    <symbol id="lu-share-2" viewBox="0 0 24 24">
      <circle cx="18" cy="5" r="3" key="gq8acd" />
      <circle cx="6" cy="12" r="3" key="w7nqdw" />
      <circle cx="18" cy="19" r="3" key="1xt0gg" />
      <line x1="8.59" x2="15.42" y1="13.51" y2="17.49" key="47mynk" />
      <line x1="15.41" x2="8.59" y1="6.51" y2="10.49" key="1n3mei" />
    </symbol>
    <symbol id="lu-sparkles" viewBox="0 0 24 24">
      <path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z" key="4pj2yx" />
      <path d="M20 3v4" key="1olli1" />
      <path d="M22 5h-4" key="1gvqau" />
      <path d="M4 17v2" key="vumght" />
      <path d="M5 18H3" key="zchphs" />
    </symbol>
    <symbol id="lu-ticket" viewBox="0 0 24 24">
      <path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z" key="qn84l0" />
      <path d="M13 5v2" key="dyzc3o" />
      <path d="M13 17v2" key="1ont0d" />
      <path d="M13 11v2" key="1wjjxi" />
    </symbol>
    <symbol id="lu-trending-up" viewBox="0 0 24 24">
      <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" key="126l90" />
      <polyline points="16 7 22 7 22 13" key="kwv8wd" />
    </symbol>
    <symbol id="lu-users" viewBox="0 0 24 24">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" key="1yyitq" />
      <circle cx="9" cy="7" r="4" key="nufk8" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" key="kshegd" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" key="1da9ce" />
    </symbol>
    </svg>
  );
}
